/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MshnctrlRouteImport } from './routes/mshnctrl'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DebugRouteImport } from './routes/debug'
import { Route as ApiManagementRouteImport } from './routes/api-management'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MshnctrlIndexRouteImport } from './routes/mshnctrl.index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as StatsUsersRouteImport } from './routes/stats/users'
import { Route as StatsSystemRouteImport } from './routes/stats/system'
import { Route as StatsSessionsRouteImport } from './routes/stats/sessions'
import { Route as MshnctrlWeatherRouteImport } from './routes/mshnctrl.weather'
import { Route as MshnctrlUncertaintyRouteImport } from './routes/mshnctrl.uncertainty'
import { Route as MshnctrlTriageRouteImport } from './routes/mshnctrl.triage'
import { Route as MshnctrlTorManagerRouteImport } from './routes/mshnctrl.tor-manager'
import { Route as MshnctrlTargetingCellDashboardRouteImport } from './routes/mshnctrl.targeting-cell-dashboard'
import { Route as MshnctrlSupplyChainRouteImport } from './routes/mshnctrl.supply-chain'
import { Route as MshnctrlStrikeOptimizerRouteImport } from './routes/mshnctrl.strike-optimizer'
import { Route as MshnctrlStrategicDirectionRouteImport } from './routes/mshnctrl.strategic-direction'
import { Route as MshnctrlStaffRouteImport } from './routes/mshnctrl.staff'
import { Route as MshnctrlSocialDomainRouteImport } from './routes/mshnctrl.social-domain'
import { Route as MshnctrlSecurityRouteImport } from './routes/mshnctrl.security'
import { Route as MshnctrlScenariosRouteImport } from './routes/mshnctrl.scenarios'
import { Route as MshnctrlRxpRouteImport } from './routes/mshnctrl.rxp'
import { Route as MshnctrlRoeRouteImport } from './routes/mshnctrl.roe'
import { Route as MshnctrlRfisRouteImport } from './routes/mshnctrl.rfis'
import { Route as MshnctrlProductsRouteImport } from './routes/mshnctrl.products'
import { Route as MshnctrlPersonnelRouteImport } from './routes/mshnctrl.personnel'
import { Route as MshnctrlOrbatRouteImport } from './routes/mshnctrl.orbat'
import { Route as MshnctrlOntologyRouteImport } from './routes/mshnctrl.ontology'
import { Route as MshnctrlMenuBuilderRouteImport } from './routes/mshnctrl.menu-builder'
import { Route as MshnctrlMdoRouteImport } from './routes/mshnctrl.mdo'
import { Route as MshnctrlLogisticsRouteImport } from './routes/mshnctrl.logistics'
import { Route as MshnctrlLegadDashboardRouteImport } from './routes/mshnctrl.legad-dashboard'
import { Route as MshnctrlJ5DashboardRouteImport } from './routes/mshnctrl.j5-dashboard'
import { Route as MshnctrlJ4DashboardRouteImport } from './routes/mshnctrl.j4-dashboard'
import { Route as MshnctrlJ3DashboardRouteImport } from './routes/mshnctrl.j3-dashboard'
import { Route as MshnctrlJ2DashboardRouteImport } from './routes/mshnctrl.j2-dashboard'
import { Route as MshnctrlInfrastructureRouteImport } from './routes/mshnctrl.infrastructure'
import { Route as MshnctrlInformationManagementRouteImport } from './routes/mshnctrl.information-management'
import { Route as MshnctrlImDashboardRouteImport } from './routes/mshnctrl/im-dashboard'
import { Route as MshnctrlGapAnalysisRouteImport } from './routes/mshnctrl.gap-analysis'
import { Route as MshnctrlFeedbackRouteImport } from './routes/mshnctrl.feedback'
import { Route as MshnctrlExternalContextRouteImport } from './routes/mshnctrl.external-context'
import { Route as MshnctrlDigitalTwinRouteImport } from './routes/mshnctrl.digital-twin'
import { Route as MshnctrlDecisionBoardRouteImport } from './routes/mshnctrl.decision-board'
import { Route as MshnctrlCopSummaryRouteImport } from './routes/mshnctrl.cop-summary'
import { Route as MshnctrlConopsRouteImport } from './routes/mshnctrl.conops'
import { Route as MshnctrlCogRouteImport } from './routes/mshnctrl.cog'
import { Route as MshnctrlCoaWargamerRouteImport } from './routes/mshnctrl.coa-wargamer'
import { Route as MshnctrlCnrRouteImport } from './routes/mshnctrl.cnr'
import { Route as MshnctrlCdeRouteImport } from './routes/mshnctrl.cde'
import { Route as MshnctrlCcirRouteImport } from './routes/mshnctrl.ccir'
import { Route as MshnctrlCampaignRouteImport } from './routes/mshnctrl.campaign'
import { Route as MshnctrlBriefingRouteImport } from './routes/mshnctrl.briefing'
import { Route as MshnctrlBrainstormingRouteImport } from './routes/mshnctrl.brainstorming'
import { Route as MshnctrlBdaRouteImport } from './routes/mshnctrl.bda'
import { Route as MshnctrlBattleRhythmRouteImport } from './routes/mshnctrl.battle-rhythm'
import { Route as MshnctrlAssumptionsRouteImport } from './routes/mshnctrl.assumptions'
import { Route as MshnctrlAssessmentRouteImport } from './routes/mshnctrl.assessment'
import { Route as MshnctrlAnalystDashboardRouteImport } from './routes/mshnctrl.analyst-dashboard'
import { Route as MshnctrlAdvisoryRouteImport } from './routes/mshnctrl.advisory'
import { Route as MshnctrlA2adRouteImport } from './routes/mshnctrl.a2ad'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminRateLimitsRouteImport } from './routes/admin/rate-limits'
import { Route as AdminNewRouteImport } from './routes/admin/new'
import { Route as AdminDiscoveryRouteImport } from './routes/admin/discovery'
import { Route as AdminAbacRouteImport } from './routes/admin/abac'
import { Route as MshnctrlTargetingIndexRouteImport } from './routes/mshnctrl.targeting.index'
import { Route as MshnctrlProposalsIndexRouteImport } from './routes/mshnctrl.proposals.index'
import { Route as AdminDiscoveryIndexRouteImport } from './routes/admin/discovery/index'
import { Route as MshnctrlTargetingTargetsRouteImport } from './routes/mshnctrl.targeting.targets'
import { Route as MshnctrlTargetingRiskRouteImport } from './routes/mshnctrl.targeting.risk'
import { Route as MshnctrlTargetingNominateRouteImport } from './routes/mshnctrl.targeting.nominate'
import { Route as MshnctrlTargetingMissionCommandRouteImport } from './routes/mshnctrl.targeting.mission-command'
import { Route as MshnctrlTargetingJtbRouteImport } from './routes/mshnctrl.targeting.jtb'
import { Route as MshnctrlTargetingIntelligenceRouteImport } from './routes/mshnctrl.targeting.intelligence'
import { Route as MshnctrlTargetingEmergencyRouteImport } from './routes/mshnctrl.targeting.emergency'
import { Route as MshnctrlTargetingEffectsRouteImport } from './routes/mshnctrl.targeting.effects'
import { Route as MshnctrlTargetingCollaborationRouteImport } from './routes/mshnctrl.targeting.collaboration'
import { Route as MshnctrlTargetingAssetsRouteImport } from './routes/mshnctrl.targeting.assets'
import { Route as MshnctrlTargetingAnalyticsRouteImport } from './routes/mshnctrl.targeting.analytics'
import { Route as MshnctrlTargetingAnalysisRouteImport } from './routes/mshnctrl.targeting.analysis'
import { Route as MshnctrlTargetingTargetIdRouteImport } from './routes/mshnctrl.targeting.$targetId'
import { Route as MshnctrlProposalsProposalIdRouteImport } from './routes/mshnctrl.proposals.$proposalId'
import { Route as MshnctrlConductSessionIdRouteImport } from './routes/mshnctrl.conduct.$sessionId'
import { Route as MshnctrlBdaCreateRouteImport } from './routes/mshnctrl.bda.create'
import { Route as MshnctrlBdaReportIdRouteImport } from './routes/mshnctrl.bda.$reportId'
import { Route as AdminDiscoveryServiceIdRouteImport } from './routes/admin/discovery/$serviceId'

const MshnctrlOplanLazyRouteImport = createFileRoute('/mshnctrl/oplan')()

const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MshnctrlRoute = MshnctrlRouteImport.update({
  id: '/mshnctrl',
  path: '/mshnctrl',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugRoute = DebugRouteImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiManagementRoute = ApiManagementRouteImport.update({
  id: '/api-management',
  path: '/api-management',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MshnctrlIndexRoute = MshnctrlIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MshnctrlRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const MshnctrlOplanLazyRoute = MshnctrlOplanLazyRouteImport.update({
  id: '/oplan',
  path: '/oplan',
  getParentRoute: () => MshnctrlRoute,
} as any).lazy(() =>
  import('./routes/mshnctrl.oplan.lazy').then((d) => d.Route),
)
const StatsUsersRoute = StatsUsersRouteImport.update({
  id: '/stats/users',
  path: '/stats/users',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsSystemRoute = StatsSystemRouteImport.update({
  id: '/stats/system',
  path: '/stats/system',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsSessionsRoute = StatsSessionsRouteImport.update({
  id: '/stats/sessions',
  path: '/stats/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const MshnctrlWeatherRoute = MshnctrlWeatherRouteImport.update({
  id: '/weather',
  path: '/weather',
  getParentRoute: () => MshnctrlRoute,
} as any)
const MshnctrlUncertaintyRoute = MshnctrlUncertaintyRouteImport.update({
  id: '/uncertainty',
  path: '/uncertainty',
  getParentRoute: () => MshnctrlRoute,
} as any)
const MshnctrlTriageRoute = MshnctrlTriageRouteImport.update({
  id: '/triage',
  path: '/triage',
  getParentRoute: () => MshnctrlRoute,
} as any).lazy(() =>
  import('./routes/mshnctrl.triage.lazy').then((d) => d.Route),
)
const MshnctrlTorManagerRoute = MshnctrlTorManagerRouteImport.update({
  id: '/tor-manager',
  path: '/tor-manager',
  getParentRoute: () => MshnctrlRoute,
} as any)
const MshnctrlTargetingCellDashboardRoute =
  MshnctrlTargetingCellDashboardRouteImport.update({
    id: '/targeting-cell-dashboard',
    path: '/targeting-cell-dashboard',
    getParentRoute: () => MshnctrlRoute,
  } as any)
const MshnctrlSupplyChainRoute = MshnctrlSupplyChainRouteImport.update({
  id: '/supply-chain',
  path: '/supply-chain',
  getParentRoute: () => MshnctrlRoute,
} as any)
const MshnctrlStrikeOptimizerRoute = MshnctrlStrikeOptimizerRouteImport.update({
  id: '/strike-optimizer',
  path: '/strike-optimizer',
  getParentRoute: () => MshnctrlRoute,
} as any)
const MshnctrlStrategicDirectionRoute =
  MshnctrlStrategicDirectionRouteImport.update({
    id: '/strategic-direction',
    path: '/strategic-direction',
    getParentRoute: () => MshnctrlRoute,
  } as any)
const MshnctrlStaffRoute = MshnctrlStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => MshnctrlRoute,
} as any)
const MshnctrlSocialDomainRoute = MshnctrlSocialDomainRouteImport.update({
  id: '/social-domain',
  path: '/social-domain',
  getParentRoute: () => MshnctrlRoute,
} as any)
const MshnctrlSecurityRoute = MshnctrlSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => MshnctrlRoute,
} as any)
const MshnctrlScenariosRoute = MshnctrlScenariosRouteImport.update({
  id: '/scenarios',
  path: '/scenarios',
  getParentRoute: () => MshnctrlRoute,
} as any)
const MshnctrlRxpRoute = MshnctrlRxpRouteImport.update({
  id: '/rxp',
  path: '/rxp',
  getParentRoute: () => MshnctrlRoute,
} as any)
const MshnctrlRoeRoute = MshnctrlRoeRouteImport.update({
  id: '/roe',
  path: '/roe',
  getParentRoute: () => MshnctrlRoute,
} as any)
const MshnctrlRfisRoute = MshnctrlRfisRouteImport.update({
  id: '/rfis',
  path: '/rfis',
  getParentRoute: () => MshnctrlRoute,
} as any)
const MshnctrlProductsRoute = MshnctrlProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => MshnctrlRoute,
} as any)
const MshnctrlPersonnelRoute = MshnctrlPersonnelRouteImport.update({
  id: '/personnel',
  path: '/personnel',
  getParentRoute: () => MshnctrlRoute,
} as any)
const MshnctrlOrbatRoute = MshnctrlOrbatRouteImport.update({
  id: '/orbat',
  path: '/orbat',
  getParentRoute: () => MshnctrlRoute,
} as any)
const MshnctrlOntologyRoute = MshnctrlOntologyRouteImport.update({
  id: '/ontology',
  path: '/ontology',
  getParentRoute: () => MshnctrlRoute,
} as any)
const MshnctrlMenuBuilderRoute = MshnctrlMenuBuilderRouteImport.update({
  id: '/menu-builder',
  path: '/menu-builder',
  getParentRoute: () => MshnctrlRoute,
} as any)
const MshnctrlMdoRoute = MshnctrlMdoRouteImport.update({
  id: '/mdo',
  path: '/mdo',
  getParentRoute: () => MshnctrlRoute,
} as any)
const MshnctrlLogisticsRoute = MshnctrlLogisticsRouteImport.update({
  id: '/logistics',
  path: '/logistics',
  getParentRoute: () => MshnctrlRoute,
} as any)
const MshnctrlLegadDashboardRoute = MshnctrlLegadDashboardRouteImport.update({
  id: '/legad-dashboard',
  path: '/legad-dashboard',
  getParentRoute: () => MshnctrlRoute,
} as any)
const MshnctrlJ5DashboardRoute = MshnctrlJ5DashboardRouteImport.update({
  id: '/j5-dashboard',
  path: '/j5-dashboard',
  getParentRoute: () => MshnctrlRoute,
} as any)
const MshnctrlJ4DashboardRoute = MshnctrlJ4DashboardRouteImport.update({
  id: '/j4-dashboard',
  path: '/j4-dashboard',
  getParentRoute: () => MshnctrlRoute,
} as any)
const MshnctrlJ3DashboardRoute = MshnctrlJ3DashboardRouteImport.update({
  id: '/j3-dashboard',
  path: '/j3-dashboard',
  getParentRoute: () => MshnctrlRoute,
} as any)
const MshnctrlJ2DashboardRoute = MshnctrlJ2DashboardRouteImport.update({
  id: '/j2-dashboard',
  path: '/j2-dashboard',
  getParentRoute: () => MshnctrlRoute,
} as any)
const MshnctrlInfrastructureRoute = MshnctrlInfrastructureRouteImport.update({
  id: '/infrastructure',
  path: '/infrastructure',
  getParentRoute: () => MshnctrlRoute,
} as any)
const MshnctrlInformationManagementRoute =
  MshnctrlInformationManagementRouteImport.update({
    id: '/information-management',
    path: '/information-management',
    getParentRoute: () => MshnctrlRoute,
  } as any)
const MshnctrlImDashboardRoute = MshnctrlImDashboardRouteImport.update({
  id: '/im-dashboard',
  path: '/im-dashboard',
  getParentRoute: () => MshnctrlRoute,
} as any)
const MshnctrlGapAnalysisRoute = MshnctrlGapAnalysisRouteImport.update({
  id: '/gap-analysis',
  path: '/gap-analysis',
  getParentRoute: () => MshnctrlRoute,
} as any).lazy(() =>
  import('./routes/mshnctrl.gap-analysis.lazy').then((d) => d.Route),
)
const MshnctrlFeedbackRoute = MshnctrlFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => MshnctrlRoute,
} as any)
const MshnctrlExternalContextRoute = MshnctrlExternalContextRouteImport.update({
  id: '/external-context',
  path: '/external-context',
  getParentRoute: () => MshnctrlRoute,
} as any)
const MshnctrlDigitalTwinRoute = MshnctrlDigitalTwinRouteImport.update({
  id: '/digital-twin',
  path: '/digital-twin',
  getParentRoute: () => MshnctrlRoute,
} as any).lazy(() =>
  import('./routes/mshnctrl.digital-twin.lazy').then((d) => d.Route),
)
const MshnctrlDecisionBoardRoute = MshnctrlDecisionBoardRouteImport.update({
  id: '/decision-board',
  path: '/decision-board',
  getParentRoute: () => MshnctrlRoute,
} as any)
const MshnctrlCopSummaryRoute = MshnctrlCopSummaryRouteImport.update({
  id: '/cop-summary',
  path: '/cop-summary',
  getParentRoute: () => MshnctrlRoute,
} as any)
const MshnctrlConopsRoute = MshnctrlConopsRouteImport.update({
  id: '/conops',
  path: '/conops',
  getParentRoute: () => MshnctrlRoute,
} as any)
const MshnctrlCogRoute = MshnctrlCogRouteImport.update({
  id: '/cog',
  path: '/cog',
  getParentRoute: () => MshnctrlRoute,
} as any)
const MshnctrlCoaWargamerRoute = MshnctrlCoaWargamerRouteImport.update({
  id: '/coa-wargamer',
  path: '/coa-wargamer',
  getParentRoute: () => MshnctrlRoute,
} as any)
const MshnctrlCnrRoute = MshnctrlCnrRouteImport.update({
  id: '/cnr',
  path: '/cnr',
  getParentRoute: () => MshnctrlRoute,
} as any)
const MshnctrlCdeRoute = MshnctrlCdeRouteImport.update({
  id: '/cde',
  path: '/cde',
  getParentRoute: () => MshnctrlRoute,
} as any)
const MshnctrlCcirRoute = MshnctrlCcirRouteImport.update({
  id: '/ccir',
  path: '/ccir',
  getParentRoute: () => MshnctrlRoute,
} as any)
const MshnctrlCampaignRoute = MshnctrlCampaignRouteImport.update({
  id: '/campaign',
  path: '/campaign',
  getParentRoute: () => MshnctrlRoute,
} as any)
const MshnctrlBriefingRoute = MshnctrlBriefingRouteImport.update({
  id: '/briefing',
  path: '/briefing',
  getParentRoute: () => MshnctrlRoute,
} as any)
const MshnctrlBrainstormingRoute = MshnctrlBrainstormingRouteImport.update({
  id: '/brainstorming',
  path: '/brainstorming',
  getParentRoute: () => MshnctrlRoute,
} as any)
const MshnctrlBdaRoute = MshnctrlBdaRouteImport.update({
  id: '/bda',
  path: '/bda',
  getParentRoute: () => MshnctrlRoute,
} as any)
const MshnctrlBattleRhythmRoute = MshnctrlBattleRhythmRouteImport.update({
  id: '/battle-rhythm',
  path: '/battle-rhythm',
  getParentRoute: () => MshnctrlRoute,
} as any).lazy(() =>
  import('./routes/mshnctrl.battle-rhythm.lazy').then((d) => d.Route),
)
const MshnctrlAssumptionsRoute = MshnctrlAssumptionsRouteImport.update({
  id: '/assumptions',
  path: '/assumptions',
  getParentRoute: () => MshnctrlRoute,
} as any)
const MshnctrlAssessmentRoute = MshnctrlAssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => MshnctrlRoute,
} as any)
const MshnctrlAnalystDashboardRoute =
  MshnctrlAnalystDashboardRouteImport.update({
    id: '/analyst-dashboard',
    path: '/analyst-dashboard',
    getParentRoute: () => MshnctrlRoute,
  } as any)
const MshnctrlAdvisoryRoute = MshnctrlAdvisoryRouteImport.update({
  id: '/advisory',
  path: '/advisory',
  getParentRoute: () => MshnctrlRoute,
} as any).lazy(() =>
  import('./routes/mshnctrl.advisory.lazy').then((d) => d.Route),
)
const MshnctrlA2adRoute = MshnctrlA2adRouteImport.update({
  id: '/a2ad',
  path: '/a2ad',
  getParentRoute: () => MshnctrlRoute,
} as any).lazy(() => import('./routes/mshnctrl.a2ad.lazy').then((d) => d.Route))
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRateLimitsRoute = AdminRateLimitsRouteImport.update({
  id: '/rate-limits',
  path: '/rate-limits',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNewRoute = AdminNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDiscoveryRoute = AdminDiscoveryRouteImport.update({
  id: '/discovery',
  path: '/discovery',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAbacRoute = AdminAbacRouteImport.update({
  id: '/abac',
  path: '/abac',
  getParentRoute: () => AdminRoute,
} as any)
const MshnctrlTargetingIndexRoute = MshnctrlTargetingIndexRouteImport.update({
  id: '/targeting/',
  path: '/targeting/',
  getParentRoute: () => MshnctrlRoute,
} as any)
const MshnctrlProposalsIndexRoute = MshnctrlProposalsIndexRouteImport.update({
  id: '/proposals/',
  path: '/proposals/',
  getParentRoute: () => MshnctrlRoute,
} as any)
const AdminDiscoveryIndexRoute = AdminDiscoveryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminDiscoveryRoute,
} as any)
const MshnctrlTargetingTargetsRoute =
  MshnctrlTargetingTargetsRouteImport.update({
    id: '/targeting/targets',
    path: '/targeting/targets',
    getParentRoute: () => MshnctrlRoute,
  } as any)
const MshnctrlTargetingRiskRoute = MshnctrlTargetingRiskRouteImport.update({
  id: '/targeting/risk',
  path: '/targeting/risk',
  getParentRoute: () => MshnctrlRoute,
} as any)
const MshnctrlTargetingNominateRoute =
  MshnctrlTargetingNominateRouteImport.update({
    id: '/targeting/nominate',
    path: '/targeting/nominate',
    getParentRoute: () => MshnctrlRoute,
  } as any)
const MshnctrlTargetingMissionCommandRoute =
  MshnctrlTargetingMissionCommandRouteImport.update({
    id: '/targeting/mission-command',
    path: '/targeting/mission-command',
    getParentRoute: () => MshnctrlRoute,
  } as any)
const MshnctrlTargetingJtbRoute = MshnctrlTargetingJtbRouteImport.update({
  id: '/targeting/jtb',
  path: '/targeting/jtb',
  getParentRoute: () => MshnctrlRoute,
} as any)
const MshnctrlTargetingIntelligenceRoute =
  MshnctrlTargetingIntelligenceRouteImport.update({
    id: '/targeting/intelligence',
    path: '/targeting/intelligence',
    getParentRoute: () => MshnctrlRoute,
  } as any)
const MshnctrlTargetingEmergencyRoute =
  MshnctrlTargetingEmergencyRouteImport.update({
    id: '/targeting/emergency',
    path: '/targeting/emergency',
    getParentRoute: () => MshnctrlRoute,
  } as any)
const MshnctrlTargetingEffectsRoute =
  MshnctrlTargetingEffectsRouteImport.update({
    id: '/targeting/effects',
    path: '/targeting/effects',
    getParentRoute: () => MshnctrlRoute,
  } as any)
const MshnctrlTargetingCollaborationRoute =
  MshnctrlTargetingCollaborationRouteImport.update({
    id: '/targeting/collaboration',
    path: '/targeting/collaboration',
    getParentRoute: () => MshnctrlRoute,
  } as any)
const MshnctrlTargetingAssetsRoute = MshnctrlTargetingAssetsRouteImport.update({
  id: '/targeting/assets',
  path: '/targeting/assets',
  getParentRoute: () => MshnctrlRoute,
} as any)
const MshnctrlTargetingAnalyticsRoute =
  MshnctrlTargetingAnalyticsRouteImport.update({
    id: '/targeting/analytics',
    path: '/targeting/analytics',
    getParentRoute: () => MshnctrlRoute,
  } as any)
const MshnctrlTargetingAnalysisRoute =
  MshnctrlTargetingAnalysisRouteImport.update({
    id: '/targeting/analysis',
    path: '/targeting/analysis',
    getParentRoute: () => MshnctrlRoute,
  } as any)
const MshnctrlTargetingTargetIdRoute =
  MshnctrlTargetingTargetIdRouteImport.update({
    id: '/targeting/$targetId',
    path: '/targeting/$targetId',
    getParentRoute: () => MshnctrlRoute,
  } as any)
const MshnctrlProposalsProposalIdRoute =
  MshnctrlProposalsProposalIdRouteImport.update({
    id: '/proposals/$proposalId',
    path: '/proposals/$proposalId',
    getParentRoute: () => MshnctrlRoute,
  } as any)
const MshnctrlConductSessionIdRoute =
  MshnctrlConductSessionIdRouteImport.update({
    id: '/conduct/$sessionId',
    path: '/conduct/$sessionId',
    getParentRoute: () => MshnctrlRoute,
  } as any).lazy(() =>
    import('./routes/mshnctrl.conduct.$sessionId.lazy').then((d) => d.Route),
  )
const MshnctrlBdaCreateRoute = MshnctrlBdaCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => MshnctrlBdaRoute,
} as any)
const MshnctrlBdaReportIdRoute = MshnctrlBdaReportIdRouteImport.update({
  id: '/$reportId',
  path: '/$reportId',
  getParentRoute: () => MshnctrlBdaRoute,
} as any)
const AdminDiscoveryServiceIdRoute = AdminDiscoveryServiceIdRouteImport.update({
  id: '/$serviceId',
  path: '/$serviceId',
  getParentRoute: () => AdminDiscoveryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/api-management': typeof ApiManagementRoute
  '/debug': typeof DebugRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/mshnctrl': typeof MshnctrlRouteWithChildren
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/admin/abac': typeof AdminAbacRoute
  '/admin/discovery': typeof AdminDiscoveryRouteWithChildren
  '/admin/new': typeof AdminNewRoute
  '/admin/rate-limits': typeof AdminRateLimitsRoute
  '/admin/users': typeof AdminUsersRoute
  '/mshnctrl/a2ad': typeof MshnctrlA2adRoute
  '/mshnctrl/advisory': typeof MshnctrlAdvisoryRoute
  '/mshnctrl/analyst-dashboard': typeof MshnctrlAnalystDashboardRoute
  '/mshnctrl/assessment': typeof MshnctrlAssessmentRoute
  '/mshnctrl/assumptions': typeof MshnctrlAssumptionsRoute
  '/mshnctrl/battle-rhythm': typeof MshnctrlBattleRhythmRoute
  '/mshnctrl/bda': typeof MshnctrlBdaRouteWithChildren
  '/mshnctrl/brainstorming': typeof MshnctrlBrainstormingRoute
  '/mshnctrl/briefing': typeof MshnctrlBriefingRoute
  '/mshnctrl/campaign': typeof MshnctrlCampaignRoute
  '/mshnctrl/ccir': typeof MshnctrlCcirRoute
  '/mshnctrl/cde': typeof MshnctrlCdeRoute
  '/mshnctrl/cnr': typeof MshnctrlCnrRoute
  '/mshnctrl/coa-wargamer': typeof MshnctrlCoaWargamerRoute
  '/mshnctrl/cog': typeof MshnctrlCogRoute
  '/mshnctrl/conops': typeof MshnctrlConopsRoute
  '/mshnctrl/cop-summary': typeof MshnctrlCopSummaryRoute
  '/mshnctrl/decision-board': typeof MshnctrlDecisionBoardRoute
  '/mshnctrl/digital-twin': typeof MshnctrlDigitalTwinRoute
  '/mshnctrl/external-context': typeof MshnctrlExternalContextRoute
  '/mshnctrl/feedback': typeof MshnctrlFeedbackRoute
  '/mshnctrl/gap-analysis': typeof MshnctrlGapAnalysisRoute
  '/mshnctrl/im-dashboard': typeof MshnctrlImDashboardRoute
  '/mshnctrl/information-management': typeof MshnctrlInformationManagementRoute
  '/mshnctrl/infrastructure': typeof MshnctrlInfrastructureRoute
  '/mshnctrl/j2-dashboard': typeof MshnctrlJ2DashboardRoute
  '/mshnctrl/j3-dashboard': typeof MshnctrlJ3DashboardRoute
  '/mshnctrl/j4-dashboard': typeof MshnctrlJ4DashboardRoute
  '/mshnctrl/j5-dashboard': typeof MshnctrlJ5DashboardRoute
  '/mshnctrl/legad-dashboard': typeof MshnctrlLegadDashboardRoute
  '/mshnctrl/logistics': typeof MshnctrlLogisticsRoute
  '/mshnctrl/mdo': typeof MshnctrlMdoRoute
  '/mshnctrl/menu-builder': typeof MshnctrlMenuBuilderRoute
  '/mshnctrl/ontology': typeof MshnctrlOntologyRoute
  '/mshnctrl/orbat': typeof MshnctrlOrbatRoute
  '/mshnctrl/personnel': typeof MshnctrlPersonnelRoute
  '/mshnctrl/products': typeof MshnctrlProductsRoute
  '/mshnctrl/rfis': typeof MshnctrlRfisRoute
  '/mshnctrl/roe': typeof MshnctrlRoeRoute
  '/mshnctrl/rxp': typeof MshnctrlRxpRoute
  '/mshnctrl/scenarios': typeof MshnctrlScenariosRoute
  '/mshnctrl/security': typeof MshnctrlSecurityRoute
  '/mshnctrl/social-domain': typeof MshnctrlSocialDomainRoute
  '/mshnctrl/staff': typeof MshnctrlStaffRoute
  '/mshnctrl/strategic-direction': typeof MshnctrlStrategicDirectionRoute
  '/mshnctrl/strike-optimizer': typeof MshnctrlStrikeOptimizerRoute
  '/mshnctrl/supply-chain': typeof MshnctrlSupplyChainRoute
  '/mshnctrl/targeting-cell-dashboard': typeof MshnctrlTargetingCellDashboardRoute
  '/mshnctrl/tor-manager': typeof MshnctrlTorManagerRoute
  '/mshnctrl/triage': typeof MshnctrlTriageRoute
  '/mshnctrl/uncertainty': typeof MshnctrlUncertaintyRoute
  '/mshnctrl/weather': typeof MshnctrlWeatherRoute
  '/stats/sessions': typeof StatsSessionsRoute
  '/stats/system': typeof StatsSystemRoute
  '/stats/users': typeof StatsUsersRoute
  '/mshnctrl/oplan': typeof MshnctrlOplanLazyRoute
  '/admin/': typeof AdminIndexRoute
  '/mshnctrl/': typeof MshnctrlIndexRoute
  '/admin/discovery/$serviceId': typeof AdminDiscoveryServiceIdRoute
  '/mshnctrl/bda/$reportId': typeof MshnctrlBdaReportIdRoute
  '/mshnctrl/bda/create': typeof MshnctrlBdaCreateRoute
  '/mshnctrl/conduct/$sessionId': typeof MshnctrlConductSessionIdRoute
  '/mshnctrl/proposals/$proposalId': typeof MshnctrlProposalsProposalIdRoute
  '/mshnctrl/targeting/$targetId': typeof MshnctrlTargetingTargetIdRoute
  '/mshnctrl/targeting/analysis': typeof MshnctrlTargetingAnalysisRoute
  '/mshnctrl/targeting/analytics': typeof MshnctrlTargetingAnalyticsRoute
  '/mshnctrl/targeting/assets': typeof MshnctrlTargetingAssetsRoute
  '/mshnctrl/targeting/collaboration': typeof MshnctrlTargetingCollaborationRoute
  '/mshnctrl/targeting/effects': typeof MshnctrlTargetingEffectsRoute
  '/mshnctrl/targeting/emergency': typeof MshnctrlTargetingEmergencyRoute
  '/mshnctrl/targeting/intelligence': typeof MshnctrlTargetingIntelligenceRoute
  '/mshnctrl/targeting/jtb': typeof MshnctrlTargetingJtbRoute
  '/mshnctrl/targeting/mission-command': typeof MshnctrlTargetingMissionCommandRoute
  '/mshnctrl/targeting/nominate': typeof MshnctrlTargetingNominateRoute
  '/mshnctrl/targeting/risk': typeof MshnctrlTargetingRiskRoute
  '/mshnctrl/targeting/targets': typeof MshnctrlTargetingTargetsRoute
  '/admin/discovery/': typeof AdminDiscoveryIndexRoute
  '/mshnctrl/proposals': typeof MshnctrlProposalsIndexRoute
  '/mshnctrl/targeting': typeof MshnctrlTargetingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api-management': typeof ApiManagementRoute
  '/debug': typeof DebugRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/admin/abac': typeof AdminAbacRoute
  '/admin/new': typeof AdminNewRoute
  '/admin/rate-limits': typeof AdminRateLimitsRoute
  '/admin/users': typeof AdminUsersRoute
  '/mshnctrl/a2ad': typeof MshnctrlA2adRoute
  '/mshnctrl/advisory': typeof MshnctrlAdvisoryRoute
  '/mshnctrl/analyst-dashboard': typeof MshnctrlAnalystDashboardRoute
  '/mshnctrl/assessment': typeof MshnctrlAssessmentRoute
  '/mshnctrl/assumptions': typeof MshnctrlAssumptionsRoute
  '/mshnctrl/battle-rhythm': typeof MshnctrlBattleRhythmRoute
  '/mshnctrl/bda': typeof MshnctrlBdaRouteWithChildren
  '/mshnctrl/brainstorming': typeof MshnctrlBrainstormingRoute
  '/mshnctrl/briefing': typeof MshnctrlBriefingRoute
  '/mshnctrl/campaign': typeof MshnctrlCampaignRoute
  '/mshnctrl/ccir': typeof MshnctrlCcirRoute
  '/mshnctrl/cde': typeof MshnctrlCdeRoute
  '/mshnctrl/cnr': typeof MshnctrlCnrRoute
  '/mshnctrl/coa-wargamer': typeof MshnctrlCoaWargamerRoute
  '/mshnctrl/cog': typeof MshnctrlCogRoute
  '/mshnctrl/conops': typeof MshnctrlConopsRoute
  '/mshnctrl/cop-summary': typeof MshnctrlCopSummaryRoute
  '/mshnctrl/decision-board': typeof MshnctrlDecisionBoardRoute
  '/mshnctrl/digital-twin': typeof MshnctrlDigitalTwinRoute
  '/mshnctrl/external-context': typeof MshnctrlExternalContextRoute
  '/mshnctrl/feedback': typeof MshnctrlFeedbackRoute
  '/mshnctrl/gap-analysis': typeof MshnctrlGapAnalysisRoute
  '/mshnctrl/im-dashboard': typeof MshnctrlImDashboardRoute
  '/mshnctrl/information-management': typeof MshnctrlInformationManagementRoute
  '/mshnctrl/infrastructure': typeof MshnctrlInfrastructureRoute
  '/mshnctrl/j2-dashboard': typeof MshnctrlJ2DashboardRoute
  '/mshnctrl/j3-dashboard': typeof MshnctrlJ3DashboardRoute
  '/mshnctrl/j4-dashboard': typeof MshnctrlJ4DashboardRoute
  '/mshnctrl/j5-dashboard': typeof MshnctrlJ5DashboardRoute
  '/mshnctrl/legad-dashboard': typeof MshnctrlLegadDashboardRoute
  '/mshnctrl/logistics': typeof MshnctrlLogisticsRoute
  '/mshnctrl/mdo': typeof MshnctrlMdoRoute
  '/mshnctrl/menu-builder': typeof MshnctrlMenuBuilderRoute
  '/mshnctrl/ontology': typeof MshnctrlOntologyRoute
  '/mshnctrl/orbat': typeof MshnctrlOrbatRoute
  '/mshnctrl/personnel': typeof MshnctrlPersonnelRoute
  '/mshnctrl/products': typeof MshnctrlProductsRoute
  '/mshnctrl/rfis': typeof MshnctrlRfisRoute
  '/mshnctrl/roe': typeof MshnctrlRoeRoute
  '/mshnctrl/rxp': typeof MshnctrlRxpRoute
  '/mshnctrl/scenarios': typeof MshnctrlScenariosRoute
  '/mshnctrl/security': typeof MshnctrlSecurityRoute
  '/mshnctrl/social-domain': typeof MshnctrlSocialDomainRoute
  '/mshnctrl/staff': typeof MshnctrlStaffRoute
  '/mshnctrl/strategic-direction': typeof MshnctrlStrategicDirectionRoute
  '/mshnctrl/strike-optimizer': typeof MshnctrlStrikeOptimizerRoute
  '/mshnctrl/supply-chain': typeof MshnctrlSupplyChainRoute
  '/mshnctrl/targeting-cell-dashboard': typeof MshnctrlTargetingCellDashboardRoute
  '/mshnctrl/tor-manager': typeof MshnctrlTorManagerRoute
  '/mshnctrl/triage': typeof MshnctrlTriageRoute
  '/mshnctrl/uncertainty': typeof MshnctrlUncertaintyRoute
  '/mshnctrl/weather': typeof MshnctrlWeatherRoute
  '/stats/sessions': typeof StatsSessionsRoute
  '/stats/system': typeof StatsSystemRoute
  '/stats/users': typeof StatsUsersRoute
  '/mshnctrl/oplan': typeof MshnctrlOplanLazyRoute
  '/admin': typeof AdminIndexRoute
  '/mshnctrl': typeof MshnctrlIndexRoute
  '/admin/discovery/$serviceId': typeof AdminDiscoveryServiceIdRoute
  '/mshnctrl/bda/$reportId': typeof MshnctrlBdaReportIdRoute
  '/mshnctrl/bda/create': typeof MshnctrlBdaCreateRoute
  '/mshnctrl/conduct/$sessionId': typeof MshnctrlConductSessionIdRoute
  '/mshnctrl/proposals/$proposalId': typeof MshnctrlProposalsProposalIdRoute
  '/mshnctrl/targeting/$targetId': typeof MshnctrlTargetingTargetIdRoute
  '/mshnctrl/targeting/analysis': typeof MshnctrlTargetingAnalysisRoute
  '/mshnctrl/targeting/analytics': typeof MshnctrlTargetingAnalyticsRoute
  '/mshnctrl/targeting/assets': typeof MshnctrlTargetingAssetsRoute
  '/mshnctrl/targeting/collaboration': typeof MshnctrlTargetingCollaborationRoute
  '/mshnctrl/targeting/effects': typeof MshnctrlTargetingEffectsRoute
  '/mshnctrl/targeting/emergency': typeof MshnctrlTargetingEmergencyRoute
  '/mshnctrl/targeting/intelligence': typeof MshnctrlTargetingIntelligenceRoute
  '/mshnctrl/targeting/jtb': typeof MshnctrlTargetingJtbRoute
  '/mshnctrl/targeting/mission-command': typeof MshnctrlTargetingMissionCommandRoute
  '/mshnctrl/targeting/nominate': typeof MshnctrlTargetingNominateRoute
  '/mshnctrl/targeting/risk': typeof MshnctrlTargetingRiskRoute
  '/mshnctrl/targeting/targets': typeof MshnctrlTargetingTargetsRoute
  '/admin/discovery': typeof AdminDiscoveryIndexRoute
  '/mshnctrl/proposals': typeof MshnctrlProposalsIndexRoute
  '/mshnctrl/targeting': typeof MshnctrlTargetingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/api-management': typeof ApiManagementRoute
  '/debug': typeof DebugRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/mshnctrl': typeof MshnctrlRouteWithChildren
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/admin/abac': typeof AdminAbacRoute
  '/admin/discovery': typeof AdminDiscoveryRouteWithChildren
  '/admin/new': typeof AdminNewRoute
  '/admin/rate-limits': typeof AdminRateLimitsRoute
  '/admin/users': typeof AdminUsersRoute
  '/mshnctrl/a2ad': typeof MshnctrlA2adRoute
  '/mshnctrl/advisory': typeof MshnctrlAdvisoryRoute
  '/mshnctrl/analyst-dashboard': typeof MshnctrlAnalystDashboardRoute
  '/mshnctrl/assessment': typeof MshnctrlAssessmentRoute
  '/mshnctrl/assumptions': typeof MshnctrlAssumptionsRoute
  '/mshnctrl/battle-rhythm': typeof MshnctrlBattleRhythmRoute
  '/mshnctrl/bda': typeof MshnctrlBdaRouteWithChildren
  '/mshnctrl/brainstorming': typeof MshnctrlBrainstormingRoute
  '/mshnctrl/briefing': typeof MshnctrlBriefingRoute
  '/mshnctrl/campaign': typeof MshnctrlCampaignRoute
  '/mshnctrl/ccir': typeof MshnctrlCcirRoute
  '/mshnctrl/cde': typeof MshnctrlCdeRoute
  '/mshnctrl/cnr': typeof MshnctrlCnrRoute
  '/mshnctrl/coa-wargamer': typeof MshnctrlCoaWargamerRoute
  '/mshnctrl/cog': typeof MshnctrlCogRoute
  '/mshnctrl/conops': typeof MshnctrlConopsRoute
  '/mshnctrl/cop-summary': typeof MshnctrlCopSummaryRoute
  '/mshnctrl/decision-board': typeof MshnctrlDecisionBoardRoute
  '/mshnctrl/digital-twin': typeof MshnctrlDigitalTwinRoute
  '/mshnctrl/external-context': typeof MshnctrlExternalContextRoute
  '/mshnctrl/feedback': typeof MshnctrlFeedbackRoute
  '/mshnctrl/gap-analysis': typeof MshnctrlGapAnalysisRoute
  '/mshnctrl/im-dashboard': typeof MshnctrlImDashboardRoute
  '/mshnctrl/information-management': typeof MshnctrlInformationManagementRoute
  '/mshnctrl/infrastructure': typeof MshnctrlInfrastructureRoute
  '/mshnctrl/j2-dashboard': typeof MshnctrlJ2DashboardRoute
  '/mshnctrl/j3-dashboard': typeof MshnctrlJ3DashboardRoute
  '/mshnctrl/j4-dashboard': typeof MshnctrlJ4DashboardRoute
  '/mshnctrl/j5-dashboard': typeof MshnctrlJ5DashboardRoute
  '/mshnctrl/legad-dashboard': typeof MshnctrlLegadDashboardRoute
  '/mshnctrl/logistics': typeof MshnctrlLogisticsRoute
  '/mshnctrl/mdo': typeof MshnctrlMdoRoute
  '/mshnctrl/menu-builder': typeof MshnctrlMenuBuilderRoute
  '/mshnctrl/ontology': typeof MshnctrlOntologyRoute
  '/mshnctrl/orbat': typeof MshnctrlOrbatRoute
  '/mshnctrl/personnel': typeof MshnctrlPersonnelRoute
  '/mshnctrl/products': typeof MshnctrlProductsRoute
  '/mshnctrl/rfis': typeof MshnctrlRfisRoute
  '/mshnctrl/roe': typeof MshnctrlRoeRoute
  '/mshnctrl/rxp': typeof MshnctrlRxpRoute
  '/mshnctrl/scenarios': typeof MshnctrlScenariosRoute
  '/mshnctrl/security': typeof MshnctrlSecurityRoute
  '/mshnctrl/social-domain': typeof MshnctrlSocialDomainRoute
  '/mshnctrl/staff': typeof MshnctrlStaffRoute
  '/mshnctrl/strategic-direction': typeof MshnctrlStrategicDirectionRoute
  '/mshnctrl/strike-optimizer': typeof MshnctrlStrikeOptimizerRoute
  '/mshnctrl/supply-chain': typeof MshnctrlSupplyChainRoute
  '/mshnctrl/targeting-cell-dashboard': typeof MshnctrlTargetingCellDashboardRoute
  '/mshnctrl/tor-manager': typeof MshnctrlTorManagerRoute
  '/mshnctrl/triage': typeof MshnctrlTriageRoute
  '/mshnctrl/uncertainty': typeof MshnctrlUncertaintyRoute
  '/mshnctrl/weather': typeof MshnctrlWeatherRoute
  '/stats/sessions': typeof StatsSessionsRoute
  '/stats/system': typeof StatsSystemRoute
  '/stats/users': typeof StatsUsersRoute
  '/mshnctrl/oplan': typeof MshnctrlOplanLazyRoute
  '/admin/': typeof AdminIndexRoute
  '/mshnctrl/': typeof MshnctrlIndexRoute
  '/admin/discovery/$serviceId': typeof AdminDiscoveryServiceIdRoute
  '/mshnctrl/bda/$reportId': typeof MshnctrlBdaReportIdRoute
  '/mshnctrl/bda/create': typeof MshnctrlBdaCreateRoute
  '/mshnctrl/conduct/$sessionId': typeof MshnctrlConductSessionIdRoute
  '/mshnctrl/proposals/$proposalId': typeof MshnctrlProposalsProposalIdRoute
  '/mshnctrl/targeting/$targetId': typeof MshnctrlTargetingTargetIdRoute
  '/mshnctrl/targeting/analysis': typeof MshnctrlTargetingAnalysisRoute
  '/mshnctrl/targeting/analytics': typeof MshnctrlTargetingAnalyticsRoute
  '/mshnctrl/targeting/assets': typeof MshnctrlTargetingAssetsRoute
  '/mshnctrl/targeting/collaboration': typeof MshnctrlTargetingCollaborationRoute
  '/mshnctrl/targeting/effects': typeof MshnctrlTargetingEffectsRoute
  '/mshnctrl/targeting/emergency': typeof MshnctrlTargetingEmergencyRoute
  '/mshnctrl/targeting/intelligence': typeof MshnctrlTargetingIntelligenceRoute
  '/mshnctrl/targeting/jtb': typeof MshnctrlTargetingJtbRoute
  '/mshnctrl/targeting/mission-command': typeof MshnctrlTargetingMissionCommandRoute
  '/mshnctrl/targeting/nominate': typeof MshnctrlTargetingNominateRoute
  '/mshnctrl/targeting/risk': typeof MshnctrlTargetingRiskRoute
  '/mshnctrl/targeting/targets': typeof MshnctrlTargetingTargetsRoute
  '/admin/discovery/': typeof AdminDiscoveryIndexRoute
  '/mshnctrl/proposals/': typeof MshnctrlProposalsIndexRoute
  '/mshnctrl/targeting/': typeof MshnctrlTargetingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/api-management'
    | '/debug'
    | '/login'
    | '/logs'
    | '/mshnctrl'
    | '/profile'
    | '/register'
    | '/reports'
    | '/admin/abac'
    | '/admin/discovery'
    | '/admin/new'
    | '/admin/rate-limits'
    | '/admin/users'
    | '/mshnctrl/a2ad'
    | '/mshnctrl/advisory'
    | '/mshnctrl/analyst-dashboard'
    | '/mshnctrl/assessment'
    | '/mshnctrl/assumptions'
    | '/mshnctrl/battle-rhythm'
    | '/mshnctrl/bda'
    | '/mshnctrl/brainstorming'
    | '/mshnctrl/briefing'
    | '/mshnctrl/campaign'
    | '/mshnctrl/ccir'
    | '/mshnctrl/cde'
    | '/mshnctrl/cnr'
    | '/mshnctrl/coa-wargamer'
    | '/mshnctrl/cog'
    | '/mshnctrl/conops'
    | '/mshnctrl/cop-summary'
    | '/mshnctrl/decision-board'
    | '/mshnctrl/digital-twin'
    | '/mshnctrl/external-context'
    | '/mshnctrl/feedback'
    | '/mshnctrl/gap-analysis'
    | '/mshnctrl/im-dashboard'
    | '/mshnctrl/information-management'
    | '/mshnctrl/infrastructure'
    | '/mshnctrl/j2-dashboard'
    | '/mshnctrl/j3-dashboard'
    | '/mshnctrl/j4-dashboard'
    | '/mshnctrl/j5-dashboard'
    | '/mshnctrl/legad-dashboard'
    | '/mshnctrl/logistics'
    | '/mshnctrl/mdo'
    | '/mshnctrl/menu-builder'
    | '/mshnctrl/ontology'
    | '/mshnctrl/orbat'
    | '/mshnctrl/personnel'
    | '/mshnctrl/products'
    | '/mshnctrl/rfis'
    | '/mshnctrl/roe'
    | '/mshnctrl/rxp'
    | '/mshnctrl/scenarios'
    | '/mshnctrl/security'
    | '/mshnctrl/social-domain'
    | '/mshnctrl/staff'
    | '/mshnctrl/strategic-direction'
    | '/mshnctrl/strike-optimizer'
    | '/mshnctrl/supply-chain'
    | '/mshnctrl/targeting-cell-dashboard'
    | '/mshnctrl/tor-manager'
    | '/mshnctrl/triage'
    | '/mshnctrl/uncertainty'
    | '/mshnctrl/weather'
    | '/stats/sessions'
    | '/stats/system'
    | '/stats/users'
    | '/mshnctrl/oplan'
    | '/admin/'
    | '/mshnctrl/'
    | '/admin/discovery/$serviceId'
    | '/mshnctrl/bda/$reportId'
    | '/mshnctrl/bda/create'
    | '/mshnctrl/conduct/$sessionId'
    | '/mshnctrl/proposals/$proposalId'
    | '/mshnctrl/targeting/$targetId'
    | '/mshnctrl/targeting/analysis'
    | '/mshnctrl/targeting/analytics'
    | '/mshnctrl/targeting/assets'
    | '/mshnctrl/targeting/collaboration'
    | '/mshnctrl/targeting/effects'
    | '/mshnctrl/targeting/emergency'
    | '/mshnctrl/targeting/intelligence'
    | '/mshnctrl/targeting/jtb'
    | '/mshnctrl/targeting/mission-command'
    | '/mshnctrl/targeting/nominate'
    | '/mshnctrl/targeting/risk'
    | '/mshnctrl/targeting/targets'
    | '/admin/discovery/'
    | '/mshnctrl/proposals'
    | '/mshnctrl/targeting'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api-management'
    | '/debug'
    | '/login'
    | '/logs'
    | '/profile'
    | '/register'
    | '/reports'
    | '/admin/abac'
    | '/admin/new'
    | '/admin/rate-limits'
    | '/admin/users'
    | '/mshnctrl/a2ad'
    | '/mshnctrl/advisory'
    | '/mshnctrl/analyst-dashboard'
    | '/mshnctrl/assessment'
    | '/mshnctrl/assumptions'
    | '/mshnctrl/battle-rhythm'
    | '/mshnctrl/bda'
    | '/mshnctrl/brainstorming'
    | '/mshnctrl/briefing'
    | '/mshnctrl/campaign'
    | '/mshnctrl/ccir'
    | '/mshnctrl/cde'
    | '/mshnctrl/cnr'
    | '/mshnctrl/coa-wargamer'
    | '/mshnctrl/cog'
    | '/mshnctrl/conops'
    | '/mshnctrl/cop-summary'
    | '/mshnctrl/decision-board'
    | '/mshnctrl/digital-twin'
    | '/mshnctrl/external-context'
    | '/mshnctrl/feedback'
    | '/mshnctrl/gap-analysis'
    | '/mshnctrl/im-dashboard'
    | '/mshnctrl/information-management'
    | '/mshnctrl/infrastructure'
    | '/mshnctrl/j2-dashboard'
    | '/mshnctrl/j3-dashboard'
    | '/mshnctrl/j4-dashboard'
    | '/mshnctrl/j5-dashboard'
    | '/mshnctrl/legad-dashboard'
    | '/mshnctrl/logistics'
    | '/mshnctrl/mdo'
    | '/mshnctrl/menu-builder'
    | '/mshnctrl/ontology'
    | '/mshnctrl/orbat'
    | '/mshnctrl/personnel'
    | '/mshnctrl/products'
    | '/mshnctrl/rfis'
    | '/mshnctrl/roe'
    | '/mshnctrl/rxp'
    | '/mshnctrl/scenarios'
    | '/mshnctrl/security'
    | '/mshnctrl/social-domain'
    | '/mshnctrl/staff'
    | '/mshnctrl/strategic-direction'
    | '/mshnctrl/strike-optimizer'
    | '/mshnctrl/supply-chain'
    | '/mshnctrl/targeting-cell-dashboard'
    | '/mshnctrl/tor-manager'
    | '/mshnctrl/triage'
    | '/mshnctrl/uncertainty'
    | '/mshnctrl/weather'
    | '/stats/sessions'
    | '/stats/system'
    | '/stats/users'
    | '/mshnctrl/oplan'
    | '/admin'
    | '/mshnctrl'
    | '/admin/discovery/$serviceId'
    | '/mshnctrl/bda/$reportId'
    | '/mshnctrl/bda/create'
    | '/mshnctrl/conduct/$sessionId'
    | '/mshnctrl/proposals/$proposalId'
    | '/mshnctrl/targeting/$targetId'
    | '/mshnctrl/targeting/analysis'
    | '/mshnctrl/targeting/analytics'
    | '/mshnctrl/targeting/assets'
    | '/mshnctrl/targeting/collaboration'
    | '/mshnctrl/targeting/effects'
    | '/mshnctrl/targeting/emergency'
    | '/mshnctrl/targeting/intelligence'
    | '/mshnctrl/targeting/jtb'
    | '/mshnctrl/targeting/mission-command'
    | '/mshnctrl/targeting/nominate'
    | '/mshnctrl/targeting/risk'
    | '/mshnctrl/targeting/targets'
    | '/admin/discovery'
    | '/mshnctrl/proposals'
    | '/mshnctrl/targeting'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/api-management'
    | '/debug'
    | '/login'
    | '/logs'
    | '/mshnctrl'
    | '/profile'
    | '/register'
    | '/reports'
    | '/admin/abac'
    | '/admin/discovery'
    | '/admin/new'
    | '/admin/rate-limits'
    | '/admin/users'
    | '/mshnctrl/a2ad'
    | '/mshnctrl/advisory'
    | '/mshnctrl/analyst-dashboard'
    | '/mshnctrl/assessment'
    | '/mshnctrl/assumptions'
    | '/mshnctrl/battle-rhythm'
    | '/mshnctrl/bda'
    | '/mshnctrl/brainstorming'
    | '/mshnctrl/briefing'
    | '/mshnctrl/campaign'
    | '/mshnctrl/ccir'
    | '/mshnctrl/cde'
    | '/mshnctrl/cnr'
    | '/mshnctrl/coa-wargamer'
    | '/mshnctrl/cog'
    | '/mshnctrl/conops'
    | '/mshnctrl/cop-summary'
    | '/mshnctrl/decision-board'
    | '/mshnctrl/digital-twin'
    | '/mshnctrl/external-context'
    | '/mshnctrl/feedback'
    | '/mshnctrl/gap-analysis'
    | '/mshnctrl/im-dashboard'
    | '/mshnctrl/information-management'
    | '/mshnctrl/infrastructure'
    | '/mshnctrl/j2-dashboard'
    | '/mshnctrl/j3-dashboard'
    | '/mshnctrl/j4-dashboard'
    | '/mshnctrl/j5-dashboard'
    | '/mshnctrl/legad-dashboard'
    | '/mshnctrl/logistics'
    | '/mshnctrl/mdo'
    | '/mshnctrl/menu-builder'
    | '/mshnctrl/ontology'
    | '/mshnctrl/orbat'
    | '/mshnctrl/personnel'
    | '/mshnctrl/products'
    | '/mshnctrl/rfis'
    | '/mshnctrl/roe'
    | '/mshnctrl/rxp'
    | '/mshnctrl/scenarios'
    | '/mshnctrl/security'
    | '/mshnctrl/social-domain'
    | '/mshnctrl/staff'
    | '/mshnctrl/strategic-direction'
    | '/mshnctrl/strike-optimizer'
    | '/mshnctrl/supply-chain'
    | '/mshnctrl/targeting-cell-dashboard'
    | '/mshnctrl/tor-manager'
    | '/mshnctrl/triage'
    | '/mshnctrl/uncertainty'
    | '/mshnctrl/weather'
    | '/stats/sessions'
    | '/stats/system'
    | '/stats/users'
    | '/mshnctrl/oplan'
    | '/admin/'
    | '/mshnctrl/'
    | '/admin/discovery/$serviceId'
    | '/mshnctrl/bda/$reportId'
    | '/mshnctrl/bda/create'
    | '/mshnctrl/conduct/$sessionId'
    | '/mshnctrl/proposals/$proposalId'
    | '/mshnctrl/targeting/$targetId'
    | '/mshnctrl/targeting/analysis'
    | '/mshnctrl/targeting/analytics'
    | '/mshnctrl/targeting/assets'
    | '/mshnctrl/targeting/collaboration'
    | '/mshnctrl/targeting/effects'
    | '/mshnctrl/targeting/emergency'
    | '/mshnctrl/targeting/intelligence'
    | '/mshnctrl/targeting/jtb'
    | '/mshnctrl/targeting/mission-command'
    | '/mshnctrl/targeting/nominate'
    | '/mshnctrl/targeting/risk'
    | '/mshnctrl/targeting/targets'
    | '/admin/discovery/'
    | '/mshnctrl/proposals/'
    | '/mshnctrl/targeting/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ApiManagementRoute: typeof ApiManagementRoute
  DebugRoute: typeof DebugRoute
  LoginRoute: typeof LoginRoute
  LogsRoute: typeof LogsRoute
  MshnctrlRoute: typeof MshnctrlRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  ReportsRoute: typeof ReportsRoute
  StatsSessionsRoute: typeof StatsSessionsRoute
  StatsSystemRoute: typeof StatsSystemRoute
  StatsUsersRoute: typeof StatsUsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mshnctrl': {
      id: '/mshnctrl'
      path: '/mshnctrl'
      fullPath: '/mshnctrl'
      preLoaderRoute: typeof MshnctrlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug': {
      id: '/debug'
      path: '/debug'
      fullPath: '/debug'
      preLoaderRoute: typeof DebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-management': {
      id: '/api-management'
      path: '/api-management'
      fullPath: '/api-management'
      preLoaderRoute: typeof ApiManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mshnctrl/': {
      id: '/mshnctrl/'
      path: '/'
      fullPath: '/mshnctrl/'
      preLoaderRoute: typeof MshnctrlIndexRouteImport
      parentRoute: typeof MshnctrlRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/mshnctrl/oplan': {
      id: '/mshnctrl/oplan'
      path: '/oplan'
      fullPath: '/mshnctrl/oplan'
      preLoaderRoute: typeof MshnctrlOplanLazyRouteImport
      parentRoute: typeof MshnctrlRoute
    }
    '/stats/users': {
      id: '/stats/users'
      path: '/stats/users'
      fullPath: '/stats/users'
      preLoaderRoute: typeof StatsUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats/system': {
      id: '/stats/system'
      path: '/stats/system'
      fullPath: '/stats/system'
      preLoaderRoute: typeof StatsSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats/sessions': {
      id: '/stats/sessions'
      path: '/stats/sessions'
      fullPath: '/stats/sessions'
      preLoaderRoute: typeof StatsSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mshnctrl/weather': {
      id: '/mshnctrl/weather'
      path: '/weather'
      fullPath: '/mshnctrl/weather'
      preLoaderRoute: typeof MshnctrlWeatherRouteImport
      parentRoute: typeof MshnctrlRoute
    }
    '/mshnctrl/uncertainty': {
      id: '/mshnctrl/uncertainty'
      path: '/uncertainty'
      fullPath: '/mshnctrl/uncertainty'
      preLoaderRoute: typeof MshnctrlUncertaintyRouteImport
      parentRoute: typeof MshnctrlRoute
    }
    '/mshnctrl/triage': {
      id: '/mshnctrl/triage'
      path: '/triage'
      fullPath: '/mshnctrl/triage'
      preLoaderRoute: typeof MshnctrlTriageRouteImport
      parentRoute: typeof MshnctrlRoute
    }
    '/mshnctrl/tor-manager': {
      id: '/mshnctrl/tor-manager'
      path: '/tor-manager'
      fullPath: '/mshnctrl/tor-manager'
      preLoaderRoute: typeof MshnctrlTorManagerRouteImport
      parentRoute: typeof MshnctrlRoute
    }
    '/mshnctrl/targeting-cell-dashboard': {
      id: '/mshnctrl/targeting-cell-dashboard'
      path: '/targeting-cell-dashboard'
      fullPath: '/mshnctrl/targeting-cell-dashboard'
      preLoaderRoute: typeof MshnctrlTargetingCellDashboardRouteImport
      parentRoute: typeof MshnctrlRoute
    }
    '/mshnctrl/supply-chain': {
      id: '/mshnctrl/supply-chain'
      path: '/supply-chain'
      fullPath: '/mshnctrl/supply-chain'
      preLoaderRoute: typeof MshnctrlSupplyChainRouteImport
      parentRoute: typeof MshnctrlRoute
    }
    '/mshnctrl/strike-optimizer': {
      id: '/mshnctrl/strike-optimizer'
      path: '/strike-optimizer'
      fullPath: '/mshnctrl/strike-optimizer'
      preLoaderRoute: typeof MshnctrlStrikeOptimizerRouteImport
      parentRoute: typeof MshnctrlRoute
    }
    '/mshnctrl/strategic-direction': {
      id: '/mshnctrl/strategic-direction'
      path: '/strategic-direction'
      fullPath: '/mshnctrl/strategic-direction'
      preLoaderRoute: typeof MshnctrlStrategicDirectionRouteImport
      parentRoute: typeof MshnctrlRoute
    }
    '/mshnctrl/staff': {
      id: '/mshnctrl/staff'
      path: '/staff'
      fullPath: '/mshnctrl/staff'
      preLoaderRoute: typeof MshnctrlStaffRouteImport
      parentRoute: typeof MshnctrlRoute
    }
    '/mshnctrl/social-domain': {
      id: '/mshnctrl/social-domain'
      path: '/social-domain'
      fullPath: '/mshnctrl/social-domain'
      preLoaderRoute: typeof MshnctrlSocialDomainRouteImport
      parentRoute: typeof MshnctrlRoute
    }
    '/mshnctrl/security': {
      id: '/mshnctrl/security'
      path: '/security'
      fullPath: '/mshnctrl/security'
      preLoaderRoute: typeof MshnctrlSecurityRouteImport
      parentRoute: typeof MshnctrlRoute
    }
    '/mshnctrl/scenarios': {
      id: '/mshnctrl/scenarios'
      path: '/scenarios'
      fullPath: '/mshnctrl/scenarios'
      preLoaderRoute: typeof MshnctrlScenariosRouteImport
      parentRoute: typeof MshnctrlRoute
    }
    '/mshnctrl/rxp': {
      id: '/mshnctrl/rxp'
      path: '/rxp'
      fullPath: '/mshnctrl/rxp'
      preLoaderRoute: typeof MshnctrlRxpRouteImport
      parentRoute: typeof MshnctrlRoute
    }
    '/mshnctrl/roe': {
      id: '/mshnctrl/roe'
      path: '/roe'
      fullPath: '/mshnctrl/roe'
      preLoaderRoute: typeof MshnctrlRoeRouteImport
      parentRoute: typeof MshnctrlRoute
    }
    '/mshnctrl/rfis': {
      id: '/mshnctrl/rfis'
      path: '/rfis'
      fullPath: '/mshnctrl/rfis'
      preLoaderRoute: typeof MshnctrlRfisRouteImport
      parentRoute: typeof MshnctrlRoute
    }
    '/mshnctrl/products': {
      id: '/mshnctrl/products'
      path: '/products'
      fullPath: '/mshnctrl/products'
      preLoaderRoute: typeof MshnctrlProductsRouteImport
      parentRoute: typeof MshnctrlRoute
    }
    '/mshnctrl/personnel': {
      id: '/mshnctrl/personnel'
      path: '/personnel'
      fullPath: '/mshnctrl/personnel'
      preLoaderRoute: typeof MshnctrlPersonnelRouteImport
      parentRoute: typeof MshnctrlRoute
    }
    '/mshnctrl/orbat': {
      id: '/mshnctrl/orbat'
      path: '/orbat'
      fullPath: '/mshnctrl/orbat'
      preLoaderRoute: typeof MshnctrlOrbatRouteImport
      parentRoute: typeof MshnctrlRoute
    }
    '/mshnctrl/ontology': {
      id: '/mshnctrl/ontology'
      path: '/ontology'
      fullPath: '/mshnctrl/ontology'
      preLoaderRoute: typeof MshnctrlOntologyRouteImport
      parentRoute: typeof MshnctrlRoute
    }
    '/mshnctrl/menu-builder': {
      id: '/mshnctrl/menu-builder'
      path: '/menu-builder'
      fullPath: '/mshnctrl/menu-builder'
      preLoaderRoute: typeof MshnctrlMenuBuilderRouteImport
      parentRoute: typeof MshnctrlRoute
    }
    '/mshnctrl/mdo': {
      id: '/mshnctrl/mdo'
      path: '/mdo'
      fullPath: '/mshnctrl/mdo'
      preLoaderRoute: typeof MshnctrlMdoRouteImport
      parentRoute: typeof MshnctrlRoute
    }
    '/mshnctrl/logistics': {
      id: '/mshnctrl/logistics'
      path: '/logistics'
      fullPath: '/mshnctrl/logistics'
      preLoaderRoute: typeof MshnctrlLogisticsRouteImport
      parentRoute: typeof MshnctrlRoute
    }
    '/mshnctrl/legad-dashboard': {
      id: '/mshnctrl/legad-dashboard'
      path: '/legad-dashboard'
      fullPath: '/mshnctrl/legad-dashboard'
      preLoaderRoute: typeof MshnctrlLegadDashboardRouteImport
      parentRoute: typeof MshnctrlRoute
    }
    '/mshnctrl/j5-dashboard': {
      id: '/mshnctrl/j5-dashboard'
      path: '/j5-dashboard'
      fullPath: '/mshnctrl/j5-dashboard'
      preLoaderRoute: typeof MshnctrlJ5DashboardRouteImport
      parentRoute: typeof MshnctrlRoute
    }
    '/mshnctrl/j4-dashboard': {
      id: '/mshnctrl/j4-dashboard'
      path: '/j4-dashboard'
      fullPath: '/mshnctrl/j4-dashboard'
      preLoaderRoute: typeof MshnctrlJ4DashboardRouteImport
      parentRoute: typeof MshnctrlRoute
    }
    '/mshnctrl/j3-dashboard': {
      id: '/mshnctrl/j3-dashboard'
      path: '/j3-dashboard'
      fullPath: '/mshnctrl/j3-dashboard'
      preLoaderRoute: typeof MshnctrlJ3DashboardRouteImport
      parentRoute: typeof MshnctrlRoute
    }
    '/mshnctrl/j2-dashboard': {
      id: '/mshnctrl/j2-dashboard'
      path: '/j2-dashboard'
      fullPath: '/mshnctrl/j2-dashboard'
      preLoaderRoute: typeof MshnctrlJ2DashboardRouteImport
      parentRoute: typeof MshnctrlRoute
    }
    '/mshnctrl/infrastructure': {
      id: '/mshnctrl/infrastructure'
      path: '/infrastructure'
      fullPath: '/mshnctrl/infrastructure'
      preLoaderRoute: typeof MshnctrlInfrastructureRouteImport
      parentRoute: typeof MshnctrlRoute
    }
    '/mshnctrl/information-management': {
      id: '/mshnctrl/information-management'
      path: '/information-management'
      fullPath: '/mshnctrl/information-management'
      preLoaderRoute: typeof MshnctrlInformationManagementRouteImport
      parentRoute: typeof MshnctrlRoute
    }
    '/mshnctrl/im-dashboard': {
      id: '/mshnctrl/im-dashboard'
      path: '/im-dashboard'
      fullPath: '/mshnctrl/im-dashboard'
      preLoaderRoute: typeof MshnctrlImDashboardRouteImport
      parentRoute: typeof MshnctrlRoute
    }
    '/mshnctrl/gap-analysis': {
      id: '/mshnctrl/gap-analysis'
      path: '/gap-analysis'
      fullPath: '/mshnctrl/gap-analysis'
      preLoaderRoute: typeof MshnctrlGapAnalysisRouteImport
      parentRoute: typeof MshnctrlRoute
    }
    '/mshnctrl/feedback': {
      id: '/mshnctrl/feedback'
      path: '/feedback'
      fullPath: '/mshnctrl/feedback'
      preLoaderRoute: typeof MshnctrlFeedbackRouteImport
      parentRoute: typeof MshnctrlRoute
    }
    '/mshnctrl/external-context': {
      id: '/mshnctrl/external-context'
      path: '/external-context'
      fullPath: '/mshnctrl/external-context'
      preLoaderRoute: typeof MshnctrlExternalContextRouteImport
      parentRoute: typeof MshnctrlRoute
    }
    '/mshnctrl/digital-twin': {
      id: '/mshnctrl/digital-twin'
      path: '/digital-twin'
      fullPath: '/mshnctrl/digital-twin'
      preLoaderRoute: typeof MshnctrlDigitalTwinRouteImport
      parentRoute: typeof MshnctrlRoute
    }
    '/mshnctrl/decision-board': {
      id: '/mshnctrl/decision-board'
      path: '/decision-board'
      fullPath: '/mshnctrl/decision-board'
      preLoaderRoute: typeof MshnctrlDecisionBoardRouteImport
      parentRoute: typeof MshnctrlRoute
    }
    '/mshnctrl/cop-summary': {
      id: '/mshnctrl/cop-summary'
      path: '/cop-summary'
      fullPath: '/mshnctrl/cop-summary'
      preLoaderRoute: typeof MshnctrlCopSummaryRouteImport
      parentRoute: typeof MshnctrlRoute
    }
    '/mshnctrl/conops': {
      id: '/mshnctrl/conops'
      path: '/conops'
      fullPath: '/mshnctrl/conops'
      preLoaderRoute: typeof MshnctrlConopsRouteImport
      parentRoute: typeof MshnctrlRoute
    }
    '/mshnctrl/cog': {
      id: '/mshnctrl/cog'
      path: '/cog'
      fullPath: '/mshnctrl/cog'
      preLoaderRoute: typeof MshnctrlCogRouteImport
      parentRoute: typeof MshnctrlRoute
    }
    '/mshnctrl/coa-wargamer': {
      id: '/mshnctrl/coa-wargamer'
      path: '/coa-wargamer'
      fullPath: '/mshnctrl/coa-wargamer'
      preLoaderRoute: typeof MshnctrlCoaWargamerRouteImport
      parentRoute: typeof MshnctrlRoute
    }
    '/mshnctrl/cnr': {
      id: '/mshnctrl/cnr'
      path: '/cnr'
      fullPath: '/mshnctrl/cnr'
      preLoaderRoute: typeof MshnctrlCnrRouteImport
      parentRoute: typeof MshnctrlRoute
    }
    '/mshnctrl/cde': {
      id: '/mshnctrl/cde'
      path: '/cde'
      fullPath: '/mshnctrl/cde'
      preLoaderRoute: typeof MshnctrlCdeRouteImport
      parentRoute: typeof MshnctrlRoute
    }
    '/mshnctrl/ccir': {
      id: '/mshnctrl/ccir'
      path: '/ccir'
      fullPath: '/mshnctrl/ccir'
      preLoaderRoute: typeof MshnctrlCcirRouteImport
      parentRoute: typeof MshnctrlRoute
    }
    '/mshnctrl/campaign': {
      id: '/mshnctrl/campaign'
      path: '/campaign'
      fullPath: '/mshnctrl/campaign'
      preLoaderRoute: typeof MshnctrlCampaignRouteImport
      parentRoute: typeof MshnctrlRoute
    }
    '/mshnctrl/briefing': {
      id: '/mshnctrl/briefing'
      path: '/briefing'
      fullPath: '/mshnctrl/briefing'
      preLoaderRoute: typeof MshnctrlBriefingRouteImport
      parentRoute: typeof MshnctrlRoute
    }
    '/mshnctrl/brainstorming': {
      id: '/mshnctrl/brainstorming'
      path: '/brainstorming'
      fullPath: '/mshnctrl/brainstorming'
      preLoaderRoute: typeof MshnctrlBrainstormingRouteImport
      parentRoute: typeof MshnctrlRoute
    }
    '/mshnctrl/bda': {
      id: '/mshnctrl/bda'
      path: '/bda'
      fullPath: '/mshnctrl/bda'
      preLoaderRoute: typeof MshnctrlBdaRouteImport
      parentRoute: typeof MshnctrlRoute
    }
    '/mshnctrl/battle-rhythm': {
      id: '/mshnctrl/battle-rhythm'
      path: '/battle-rhythm'
      fullPath: '/mshnctrl/battle-rhythm'
      preLoaderRoute: typeof MshnctrlBattleRhythmRouteImport
      parentRoute: typeof MshnctrlRoute
    }
    '/mshnctrl/assumptions': {
      id: '/mshnctrl/assumptions'
      path: '/assumptions'
      fullPath: '/mshnctrl/assumptions'
      preLoaderRoute: typeof MshnctrlAssumptionsRouteImport
      parentRoute: typeof MshnctrlRoute
    }
    '/mshnctrl/assessment': {
      id: '/mshnctrl/assessment'
      path: '/assessment'
      fullPath: '/mshnctrl/assessment'
      preLoaderRoute: typeof MshnctrlAssessmentRouteImport
      parentRoute: typeof MshnctrlRoute
    }
    '/mshnctrl/analyst-dashboard': {
      id: '/mshnctrl/analyst-dashboard'
      path: '/analyst-dashboard'
      fullPath: '/mshnctrl/analyst-dashboard'
      preLoaderRoute: typeof MshnctrlAnalystDashboardRouteImport
      parentRoute: typeof MshnctrlRoute
    }
    '/mshnctrl/advisory': {
      id: '/mshnctrl/advisory'
      path: '/advisory'
      fullPath: '/mshnctrl/advisory'
      preLoaderRoute: typeof MshnctrlAdvisoryRouteImport
      parentRoute: typeof MshnctrlRoute
    }
    '/mshnctrl/a2ad': {
      id: '/mshnctrl/a2ad'
      path: '/a2ad'
      fullPath: '/mshnctrl/a2ad'
      preLoaderRoute: typeof MshnctrlA2adRouteImport
      parentRoute: typeof MshnctrlRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rate-limits': {
      id: '/admin/rate-limits'
      path: '/rate-limits'
      fullPath: '/admin/rate-limits'
      preLoaderRoute: typeof AdminRateLimitsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/new': {
      id: '/admin/new'
      path: '/new'
      fullPath: '/admin/new'
      preLoaderRoute: typeof AdminNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/discovery': {
      id: '/admin/discovery'
      path: '/discovery'
      fullPath: '/admin/discovery'
      preLoaderRoute: typeof AdminDiscoveryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/abac': {
      id: '/admin/abac'
      path: '/abac'
      fullPath: '/admin/abac'
      preLoaderRoute: typeof AdminAbacRouteImport
      parentRoute: typeof AdminRoute
    }
    '/mshnctrl/targeting/': {
      id: '/mshnctrl/targeting/'
      path: '/targeting'
      fullPath: '/mshnctrl/targeting'
      preLoaderRoute: typeof MshnctrlTargetingIndexRouteImport
      parentRoute: typeof MshnctrlRoute
    }
    '/mshnctrl/proposals/': {
      id: '/mshnctrl/proposals/'
      path: '/proposals'
      fullPath: '/mshnctrl/proposals'
      preLoaderRoute: typeof MshnctrlProposalsIndexRouteImport
      parentRoute: typeof MshnctrlRoute
    }
    '/admin/discovery/': {
      id: '/admin/discovery/'
      path: '/'
      fullPath: '/admin/discovery/'
      preLoaderRoute: typeof AdminDiscoveryIndexRouteImport
      parentRoute: typeof AdminDiscoveryRoute
    }
    '/mshnctrl/targeting/targets': {
      id: '/mshnctrl/targeting/targets'
      path: '/targeting/targets'
      fullPath: '/mshnctrl/targeting/targets'
      preLoaderRoute: typeof MshnctrlTargetingTargetsRouteImport
      parentRoute: typeof MshnctrlRoute
    }
    '/mshnctrl/targeting/risk': {
      id: '/mshnctrl/targeting/risk'
      path: '/targeting/risk'
      fullPath: '/mshnctrl/targeting/risk'
      preLoaderRoute: typeof MshnctrlTargetingRiskRouteImport
      parentRoute: typeof MshnctrlRoute
    }
    '/mshnctrl/targeting/nominate': {
      id: '/mshnctrl/targeting/nominate'
      path: '/targeting/nominate'
      fullPath: '/mshnctrl/targeting/nominate'
      preLoaderRoute: typeof MshnctrlTargetingNominateRouteImport
      parentRoute: typeof MshnctrlRoute
    }
    '/mshnctrl/targeting/mission-command': {
      id: '/mshnctrl/targeting/mission-command'
      path: '/targeting/mission-command'
      fullPath: '/mshnctrl/targeting/mission-command'
      preLoaderRoute: typeof MshnctrlTargetingMissionCommandRouteImport
      parentRoute: typeof MshnctrlRoute
    }
    '/mshnctrl/targeting/jtb': {
      id: '/mshnctrl/targeting/jtb'
      path: '/targeting/jtb'
      fullPath: '/mshnctrl/targeting/jtb'
      preLoaderRoute: typeof MshnctrlTargetingJtbRouteImport
      parentRoute: typeof MshnctrlRoute
    }
    '/mshnctrl/targeting/intelligence': {
      id: '/mshnctrl/targeting/intelligence'
      path: '/targeting/intelligence'
      fullPath: '/mshnctrl/targeting/intelligence'
      preLoaderRoute: typeof MshnctrlTargetingIntelligenceRouteImport
      parentRoute: typeof MshnctrlRoute
    }
    '/mshnctrl/targeting/emergency': {
      id: '/mshnctrl/targeting/emergency'
      path: '/targeting/emergency'
      fullPath: '/mshnctrl/targeting/emergency'
      preLoaderRoute: typeof MshnctrlTargetingEmergencyRouteImport
      parentRoute: typeof MshnctrlRoute
    }
    '/mshnctrl/targeting/effects': {
      id: '/mshnctrl/targeting/effects'
      path: '/targeting/effects'
      fullPath: '/mshnctrl/targeting/effects'
      preLoaderRoute: typeof MshnctrlTargetingEffectsRouteImport
      parentRoute: typeof MshnctrlRoute
    }
    '/mshnctrl/targeting/collaboration': {
      id: '/mshnctrl/targeting/collaboration'
      path: '/targeting/collaboration'
      fullPath: '/mshnctrl/targeting/collaboration'
      preLoaderRoute: typeof MshnctrlTargetingCollaborationRouteImport
      parentRoute: typeof MshnctrlRoute
    }
    '/mshnctrl/targeting/assets': {
      id: '/mshnctrl/targeting/assets'
      path: '/targeting/assets'
      fullPath: '/mshnctrl/targeting/assets'
      preLoaderRoute: typeof MshnctrlTargetingAssetsRouteImport
      parentRoute: typeof MshnctrlRoute
    }
    '/mshnctrl/targeting/analytics': {
      id: '/mshnctrl/targeting/analytics'
      path: '/targeting/analytics'
      fullPath: '/mshnctrl/targeting/analytics'
      preLoaderRoute: typeof MshnctrlTargetingAnalyticsRouteImport
      parentRoute: typeof MshnctrlRoute
    }
    '/mshnctrl/targeting/analysis': {
      id: '/mshnctrl/targeting/analysis'
      path: '/targeting/analysis'
      fullPath: '/mshnctrl/targeting/analysis'
      preLoaderRoute: typeof MshnctrlTargetingAnalysisRouteImport
      parentRoute: typeof MshnctrlRoute
    }
    '/mshnctrl/targeting/$targetId': {
      id: '/mshnctrl/targeting/$targetId'
      path: '/targeting/$targetId'
      fullPath: '/mshnctrl/targeting/$targetId'
      preLoaderRoute: typeof MshnctrlTargetingTargetIdRouteImport
      parentRoute: typeof MshnctrlRoute
    }
    '/mshnctrl/proposals/$proposalId': {
      id: '/mshnctrl/proposals/$proposalId'
      path: '/proposals/$proposalId'
      fullPath: '/mshnctrl/proposals/$proposalId'
      preLoaderRoute: typeof MshnctrlProposalsProposalIdRouteImport
      parentRoute: typeof MshnctrlRoute
    }
    '/mshnctrl/conduct/$sessionId': {
      id: '/mshnctrl/conduct/$sessionId'
      path: '/conduct/$sessionId'
      fullPath: '/mshnctrl/conduct/$sessionId'
      preLoaderRoute: typeof MshnctrlConductSessionIdRouteImport
      parentRoute: typeof MshnctrlRoute
    }
    '/mshnctrl/bda/create': {
      id: '/mshnctrl/bda/create'
      path: '/create'
      fullPath: '/mshnctrl/bda/create'
      preLoaderRoute: typeof MshnctrlBdaCreateRouteImport
      parentRoute: typeof MshnctrlBdaRoute
    }
    '/mshnctrl/bda/$reportId': {
      id: '/mshnctrl/bda/$reportId'
      path: '/$reportId'
      fullPath: '/mshnctrl/bda/$reportId'
      preLoaderRoute: typeof MshnctrlBdaReportIdRouteImport
      parentRoute: typeof MshnctrlBdaRoute
    }
    '/admin/discovery/$serviceId': {
      id: '/admin/discovery/$serviceId'
      path: '/$serviceId'
      fullPath: '/admin/discovery/$serviceId'
      preLoaderRoute: typeof AdminDiscoveryServiceIdRouteImport
      parentRoute: typeof AdminDiscoveryRoute
    }
  }
}

interface AdminDiscoveryRouteChildren {
  AdminDiscoveryServiceIdRoute: typeof AdminDiscoveryServiceIdRoute
  AdminDiscoveryIndexRoute: typeof AdminDiscoveryIndexRoute
}

const AdminDiscoveryRouteChildren: AdminDiscoveryRouteChildren = {
  AdminDiscoveryServiceIdRoute: AdminDiscoveryServiceIdRoute,
  AdminDiscoveryIndexRoute: AdminDiscoveryIndexRoute,
}

const AdminDiscoveryRouteWithChildren = AdminDiscoveryRoute._addFileChildren(
  AdminDiscoveryRouteChildren,
)

interface AdminRouteChildren {
  AdminAbacRoute: typeof AdminAbacRoute
  AdminDiscoveryRoute: typeof AdminDiscoveryRouteWithChildren
  AdminNewRoute: typeof AdminNewRoute
  AdminRateLimitsRoute: typeof AdminRateLimitsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAbacRoute: AdminAbacRoute,
  AdminDiscoveryRoute: AdminDiscoveryRouteWithChildren,
  AdminNewRoute: AdminNewRoute,
  AdminRateLimitsRoute: AdminRateLimitsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface MshnctrlBdaRouteChildren {
  MshnctrlBdaReportIdRoute: typeof MshnctrlBdaReportIdRoute
  MshnctrlBdaCreateRoute: typeof MshnctrlBdaCreateRoute
}

const MshnctrlBdaRouteChildren: MshnctrlBdaRouteChildren = {
  MshnctrlBdaReportIdRoute: MshnctrlBdaReportIdRoute,
  MshnctrlBdaCreateRoute: MshnctrlBdaCreateRoute,
}

const MshnctrlBdaRouteWithChildren = MshnctrlBdaRoute._addFileChildren(
  MshnctrlBdaRouteChildren,
)

interface MshnctrlRouteChildren {
  MshnctrlA2adRoute: typeof MshnctrlA2adRoute
  MshnctrlAdvisoryRoute: typeof MshnctrlAdvisoryRoute
  MshnctrlAnalystDashboardRoute: typeof MshnctrlAnalystDashboardRoute
  MshnctrlAssessmentRoute: typeof MshnctrlAssessmentRoute
  MshnctrlAssumptionsRoute: typeof MshnctrlAssumptionsRoute
  MshnctrlBattleRhythmRoute: typeof MshnctrlBattleRhythmRoute
  MshnctrlBdaRoute: typeof MshnctrlBdaRouteWithChildren
  MshnctrlBrainstormingRoute: typeof MshnctrlBrainstormingRoute
  MshnctrlBriefingRoute: typeof MshnctrlBriefingRoute
  MshnctrlCampaignRoute: typeof MshnctrlCampaignRoute
  MshnctrlCcirRoute: typeof MshnctrlCcirRoute
  MshnctrlCdeRoute: typeof MshnctrlCdeRoute
  MshnctrlCnrRoute: typeof MshnctrlCnrRoute
  MshnctrlCoaWargamerRoute: typeof MshnctrlCoaWargamerRoute
  MshnctrlCogRoute: typeof MshnctrlCogRoute
  MshnctrlConopsRoute: typeof MshnctrlConopsRoute
  MshnctrlCopSummaryRoute: typeof MshnctrlCopSummaryRoute
  MshnctrlDecisionBoardRoute: typeof MshnctrlDecisionBoardRoute
  MshnctrlDigitalTwinRoute: typeof MshnctrlDigitalTwinRoute
  MshnctrlExternalContextRoute: typeof MshnctrlExternalContextRoute
  MshnctrlFeedbackRoute: typeof MshnctrlFeedbackRoute
  MshnctrlGapAnalysisRoute: typeof MshnctrlGapAnalysisRoute
  MshnctrlImDashboardRoute: typeof MshnctrlImDashboardRoute
  MshnctrlInformationManagementRoute: typeof MshnctrlInformationManagementRoute
  MshnctrlInfrastructureRoute: typeof MshnctrlInfrastructureRoute
  MshnctrlJ2DashboardRoute: typeof MshnctrlJ2DashboardRoute
  MshnctrlJ3DashboardRoute: typeof MshnctrlJ3DashboardRoute
  MshnctrlJ4DashboardRoute: typeof MshnctrlJ4DashboardRoute
  MshnctrlJ5DashboardRoute: typeof MshnctrlJ5DashboardRoute
  MshnctrlLegadDashboardRoute: typeof MshnctrlLegadDashboardRoute
  MshnctrlLogisticsRoute: typeof MshnctrlLogisticsRoute
  MshnctrlMdoRoute: typeof MshnctrlMdoRoute
  MshnctrlMenuBuilderRoute: typeof MshnctrlMenuBuilderRoute
  MshnctrlOntologyRoute: typeof MshnctrlOntologyRoute
  MshnctrlOrbatRoute: typeof MshnctrlOrbatRoute
  MshnctrlPersonnelRoute: typeof MshnctrlPersonnelRoute
  MshnctrlProductsRoute: typeof MshnctrlProductsRoute
  MshnctrlRfisRoute: typeof MshnctrlRfisRoute
  MshnctrlRoeRoute: typeof MshnctrlRoeRoute
  MshnctrlRxpRoute: typeof MshnctrlRxpRoute
  MshnctrlScenariosRoute: typeof MshnctrlScenariosRoute
  MshnctrlSecurityRoute: typeof MshnctrlSecurityRoute
  MshnctrlSocialDomainRoute: typeof MshnctrlSocialDomainRoute
  MshnctrlStaffRoute: typeof MshnctrlStaffRoute
  MshnctrlStrategicDirectionRoute: typeof MshnctrlStrategicDirectionRoute
  MshnctrlStrikeOptimizerRoute: typeof MshnctrlStrikeOptimizerRoute
  MshnctrlSupplyChainRoute: typeof MshnctrlSupplyChainRoute
  MshnctrlTargetingCellDashboardRoute: typeof MshnctrlTargetingCellDashboardRoute
  MshnctrlTorManagerRoute: typeof MshnctrlTorManagerRoute
  MshnctrlTriageRoute: typeof MshnctrlTriageRoute
  MshnctrlUncertaintyRoute: typeof MshnctrlUncertaintyRoute
  MshnctrlWeatherRoute: typeof MshnctrlWeatherRoute
  MshnctrlOplanLazyRoute: typeof MshnctrlOplanLazyRoute
  MshnctrlIndexRoute: typeof MshnctrlIndexRoute
  MshnctrlConductSessionIdRoute: typeof MshnctrlConductSessionIdRoute
  MshnctrlProposalsProposalIdRoute: typeof MshnctrlProposalsProposalIdRoute
  MshnctrlTargetingTargetIdRoute: typeof MshnctrlTargetingTargetIdRoute
  MshnctrlTargetingAnalysisRoute: typeof MshnctrlTargetingAnalysisRoute
  MshnctrlTargetingAnalyticsRoute: typeof MshnctrlTargetingAnalyticsRoute
  MshnctrlTargetingAssetsRoute: typeof MshnctrlTargetingAssetsRoute
  MshnctrlTargetingCollaborationRoute: typeof MshnctrlTargetingCollaborationRoute
  MshnctrlTargetingEffectsRoute: typeof MshnctrlTargetingEffectsRoute
  MshnctrlTargetingEmergencyRoute: typeof MshnctrlTargetingEmergencyRoute
  MshnctrlTargetingIntelligenceRoute: typeof MshnctrlTargetingIntelligenceRoute
  MshnctrlTargetingJtbRoute: typeof MshnctrlTargetingJtbRoute
  MshnctrlTargetingMissionCommandRoute: typeof MshnctrlTargetingMissionCommandRoute
  MshnctrlTargetingNominateRoute: typeof MshnctrlTargetingNominateRoute
  MshnctrlTargetingRiskRoute: typeof MshnctrlTargetingRiskRoute
  MshnctrlTargetingTargetsRoute: typeof MshnctrlTargetingTargetsRoute
  MshnctrlProposalsIndexRoute: typeof MshnctrlProposalsIndexRoute
  MshnctrlTargetingIndexRoute: typeof MshnctrlTargetingIndexRoute
}

const MshnctrlRouteChildren: MshnctrlRouteChildren = {
  MshnctrlA2adRoute: MshnctrlA2adRoute,
  MshnctrlAdvisoryRoute: MshnctrlAdvisoryRoute,
  MshnctrlAnalystDashboardRoute: MshnctrlAnalystDashboardRoute,
  MshnctrlAssessmentRoute: MshnctrlAssessmentRoute,
  MshnctrlAssumptionsRoute: MshnctrlAssumptionsRoute,
  MshnctrlBattleRhythmRoute: MshnctrlBattleRhythmRoute,
  MshnctrlBdaRoute: MshnctrlBdaRouteWithChildren,
  MshnctrlBrainstormingRoute: MshnctrlBrainstormingRoute,
  MshnctrlBriefingRoute: MshnctrlBriefingRoute,
  MshnctrlCampaignRoute: MshnctrlCampaignRoute,
  MshnctrlCcirRoute: MshnctrlCcirRoute,
  MshnctrlCdeRoute: MshnctrlCdeRoute,
  MshnctrlCnrRoute: MshnctrlCnrRoute,
  MshnctrlCoaWargamerRoute: MshnctrlCoaWargamerRoute,
  MshnctrlCogRoute: MshnctrlCogRoute,
  MshnctrlConopsRoute: MshnctrlConopsRoute,
  MshnctrlCopSummaryRoute: MshnctrlCopSummaryRoute,
  MshnctrlDecisionBoardRoute: MshnctrlDecisionBoardRoute,
  MshnctrlDigitalTwinRoute: MshnctrlDigitalTwinRoute,
  MshnctrlExternalContextRoute: MshnctrlExternalContextRoute,
  MshnctrlFeedbackRoute: MshnctrlFeedbackRoute,
  MshnctrlGapAnalysisRoute: MshnctrlGapAnalysisRoute,
  MshnctrlImDashboardRoute: MshnctrlImDashboardRoute,
  MshnctrlInformationManagementRoute: MshnctrlInformationManagementRoute,
  MshnctrlInfrastructureRoute: MshnctrlInfrastructureRoute,
  MshnctrlJ2DashboardRoute: MshnctrlJ2DashboardRoute,
  MshnctrlJ3DashboardRoute: MshnctrlJ3DashboardRoute,
  MshnctrlJ4DashboardRoute: MshnctrlJ4DashboardRoute,
  MshnctrlJ5DashboardRoute: MshnctrlJ5DashboardRoute,
  MshnctrlLegadDashboardRoute: MshnctrlLegadDashboardRoute,
  MshnctrlLogisticsRoute: MshnctrlLogisticsRoute,
  MshnctrlMdoRoute: MshnctrlMdoRoute,
  MshnctrlMenuBuilderRoute: MshnctrlMenuBuilderRoute,
  MshnctrlOntologyRoute: MshnctrlOntologyRoute,
  MshnctrlOrbatRoute: MshnctrlOrbatRoute,
  MshnctrlPersonnelRoute: MshnctrlPersonnelRoute,
  MshnctrlProductsRoute: MshnctrlProductsRoute,
  MshnctrlRfisRoute: MshnctrlRfisRoute,
  MshnctrlRoeRoute: MshnctrlRoeRoute,
  MshnctrlRxpRoute: MshnctrlRxpRoute,
  MshnctrlScenariosRoute: MshnctrlScenariosRoute,
  MshnctrlSecurityRoute: MshnctrlSecurityRoute,
  MshnctrlSocialDomainRoute: MshnctrlSocialDomainRoute,
  MshnctrlStaffRoute: MshnctrlStaffRoute,
  MshnctrlStrategicDirectionRoute: MshnctrlStrategicDirectionRoute,
  MshnctrlStrikeOptimizerRoute: MshnctrlStrikeOptimizerRoute,
  MshnctrlSupplyChainRoute: MshnctrlSupplyChainRoute,
  MshnctrlTargetingCellDashboardRoute: MshnctrlTargetingCellDashboardRoute,
  MshnctrlTorManagerRoute: MshnctrlTorManagerRoute,
  MshnctrlTriageRoute: MshnctrlTriageRoute,
  MshnctrlUncertaintyRoute: MshnctrlUncertaintyRoute,
  MshnctrlWeatherRoute: MshnctrlWeatherRoute,
  MshnctrlOplanLazyRoute: MshnctrlOplanLazyRoute,
  MshnctrlIndexRoute: MshnctrlIndexRoute,
  MshnctrlConductSessionIdRoute: MshnctrlConductSessionIdRoute,
  MshnctrlProposalsProposalIdRoute: MshnctrlProposalsProposalIdRoute,
  MshnctrlTargetingTargetIdRoute: MshnctrlTargetingTargetIdRoute,
  MshnctrlTargetingAnalysisRoute: MshnctrlTargetingAnalysisRoute,
  MshnctrlTargetingAnalyticsRoute: MshnctrlTargetingAnalyticsRoute,
  MshnctrlTargetingAssetsRoute: MshnctrlTargetingAssetsRoute,
  MshnctrlTargetingCollaborationRoute: MshnctrlTargetingCollaborationRoute,
  MshnctrlTargetingEffectsRoute: MshnctrlTargetingEffectsRoute,
  MshnctrlTargetingEmergencyRoute: MshnctrlTargetingEmergencyRoute,
  MshnctrlTargetingIntelligenceRoute: MshnctrlTargetingIntelligenceRoute,
  MshnctrlTargetingJtbRoute: MshnctrlTargetingJtbRoute,
  MshnctrlTargetingMissionCommandRoute: MshnctrlTargetingMissionCommandRoute,
  MshnctrlTargetingNominateRoute: MshnctrlTargetingNominateRoute,
  MshnctrlTargetingRiskRoute: MshnctrlTargetingRiskRoute,
  MshnctrlTargetingTargetsRoute: MshnctrlTargetingTargetsRoute,
  MshnctrlProposalsIndexRoute: MshnctrlProposalsIndexRoute,
  MshnctrlTargetingIndexRoute: MshnctrlTargetingIndexRoute,
}

const MshnctrlRouteWithChildren = MshnctrlRoute._addFileChildren(
  MshnctrlRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ApiManagementRoute: ApiManagementRoute,
  DebugRoute: DebugRoute,
  LoginRoute: LoginRoute,
  LogsRoute: LogsRoute,
  MshnctrlRoute: MshnctrlRouteWithChildren,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  ReportsRoute: ReportsRoute,
  StatsSessionsRoute: StatsSessionsRoute,
  StatsSystemRoute: StatsSystemRoute,
  StatsUsersRoute: StatsUsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
