/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as SmartopsRouteImport } from './routes/smartops'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DebugRouteImport } from './routes/debug'
import { Route as ApiManagementRouteImport } from './routes/api-management'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SmartopsIndexRouteImport } from './routes/smartops.index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as StatsUsersRouteImport } from './routes/stats/users'
import { Route as StatsSystemRouteImport } from './routes/stats/system'
import { Route as StatsSessionsRouteImport } from './routes/stats/sessions'
import { Route as SmartopsWeatherRouteImport } from './routes/smartops.weather'
import { Route as SmartopsUncertaintyRouteImport } from './routes/smartops.uncertainty'
import { Route as SmartopsTriageRouteImport } from './routes/smartops.triage'
import { Route as SmartopsTorManagerRouteImport } from './routes/smartops.tor-manager'
import { Route as SmartopsTargetingCellDashboardRouteImport } from './routes/smartops.targeting-cell-dashboard'
import { Route as SmartopsSupplyChainRouteImport } from './routes/smartops.supply-chain'
import { Route as SmartopsStrikeOptimizerRouteImport } from './routes/smartops.strike-optimizer'
import { Route as SmartopsStrategicDirectionRouteImport } from './routes/smartops.strategic-direction'
import { Route as SmartopsStaffRouteImport } from './routes/smartops.staff'
import { Route as SmartopsSocialDomainRouteImport } from './routes/smartops.social-domain'
import { Route as SmartopsSecurityRouteImport } from './routes/smartops.security'
import { Route as SmartopsScenariosRouteImport } from './routes/smartops.scenarios'
import { Route as SmartopsRxpRouteImport } from './routes/smartops.rxp'
import { Route as SmartopsRoeRouteImport } from './routes/smartops.roe'
import { Route as SmartopsRfisRouteImport } from './routes/smartops.rfis'
import { Route as SmartopsProductsRouteImport } from './routes/smartops.products'
import { Route as SmartopsPersonnelRouteImport } from './routes/smartops.personnel'
import { Route as SmartopsOrbatRouteImport } from './routes/smartops.orbat'
import { Route as SmartopsOntologyRouteImport } from './routes/smartops.ontology'
import { Route as SmartopsMenuBuilderRouteImport } from './routes/smartops.menu-builder'
import { Route as SmartopsMdoRouteImport } from './routes/smartops.mdo'
import { Route as SmartopsLogisticsRouteImport } from './routes/smartops.logistics'
import { Route as SmartopsLegadDashboardRouteImport } from './routes/smartops.legad-dashboard'
import { Route as SmartopsJ5DashboardRouteImport } from './routes/smartops.j5-dashboard'
import { Route as SmartopsJ4DashboardRouteImport } from './routes/smartops.j4-dashboard'
import { Route as SmartopsJ3DashboardRouteImport } from './routes/smartops.j3-dashboard'
import { Route as SmartopsJ2DashboardRouteImport } from './routes/smartops.j2-dashboard'
import { Route as SmartopsInfrastructureRouteImport } from './routes/smartops.infrastructure'
import { Route as SmartopsInformationManagementRouteImport } from './routes/smartops.information-management'
import { Route as SmartopsImDashboardRouteImport } from './routes/smartops/im-dashboard'
import { Route as SmartopsGapAnalysisRouteImport } from './routes/smartops.gap-analysis'
import { Route as SmartopsFeedbackRouteImport } from './routes/smartops.feedback'
import { Route as SmartopsExternalContextRouteImport } from './routes/smartops.external-context'
import { Route as SmartopsDigitalTwinRouteImport } from './routes/smartops.digital-twin'
import { Route as SmartopsDecisionBoardRouteImport } from './routes/smartops.decision-board'
import { Route as SmartopsCopSummaryRouteImport } from './routes/smartops.cop-summary'
import { Route as SmartopsConopsRouteImport } from './routes/smartops.conops'
import { Route as SmartopsCogRouteImport } from './routes/smartops.cog'
import { Route as SmartopsCoaWargamerRouteImport } from './routes/smartops.coa-wargamer'
import { Route as SmartopsCnrRouteImport } from './routes/smartops.cnr'
import { Route as SmartopsCdeRouteImport } from './routes/smartops.cde'
import { Route as SmartopsCcirRouteImport } from './routes/smartops.ccir'
import { Route as SmartopsCampaignRouteImport } from './routes/smartops.campaign'
import { Route as SmartopsBriefingRouteImport } from './routes/smartops.briefing'
import { Route as SmartopsBrainstormingRouteImport } from './routes/smartops.brainstorming'
import { Route as SmartopsBdaRouteImport } from './routes/smartops.bda'
import { Route as SmartopsBattleRhythmRouteImport } from './routes/smartops.battle-rhythm'
import { Route as SmartopsAssumptionsRouteImport } from './routes/smartops.assumptions'
import { Route as SmartopsAssessmentRouteImport } from './routes/smartops.assessment'
import { Route as SmartopsAnalystDashboardRouteImport } from './routes/smartops.analyst-dashboard'
import { Route as SmartopsAdvisoryRouteImport } from './routes/smartops.advisory'
import { Route as SmartopsA2adRouteImport } from './routes/smartops.a2ad'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminRateLimitsRouteImport } from './routes/admin/rate-limits'
import { Route as AdminNewRouteImport } from './routes/admin/new'
import { Route as AdminDiscoveryRouteImport } from './routes/admin/discovery'
import { Route as AdminAbacRouteImport } from './routes/admin/abac'
import { Route as SmartopsTargetingIndexRouteImport } from './routes/smartops.targeting.index'
import { Route as SmartopsProposalsIndexRouteImport } from './routes/smartops.proposals.index'
import { Route as AdminDiscoveryIndexRouteImport } from './routes/admin/discovery/index'
import { Route as SmartopsTargetingTargetsRouteImport } from './routes/smartops.targeting.targets'
import { Route as SmartopsTargetingRiskRouteImport } from './routes/smartops.targeting.risk'
import { Route as SmartopsTargetingNominateRouteImport } from './routes/smartops.targeting.nominate'
import { Route as SmartopsTargetingMissionCommandRouteImport } from './routes/smartops.targeting.mission-command'
import { Route as SmartopsTargetingJtbRouteImport } from './routes/smartops.targeting.jtb'
import { Route as SmartopsTargetingIntelligenceRouteImport } from './routes/smartops.targeting.intelligence'
import { Route as SmartopsTargetingEmergencyRouteImport } from './routes/smartops.targeting.emergency'
import { Route as SmartopsTargetingEffectsRouteImport } from './routes/smartops.targeting.effects'
import { Route as SmartopsTargetingCollaborationRouteImport } from './routes/smartops.targeting.collaboration'
import { Route as SmartopsTargetingAssetsRouteImport } from './routes/smartops.targeting.assets'
import { Route as SmartopsTargetingAnalyticsRouteImport } from './routes/smartops.targeting.analytics'
import { Route as SmartopsTargetingAnalysisRouteImport } from './routes/smartops.targeting.analysis'
import { Route as SmartopsTargetingTargetIdRouteImport } from './routes/smartops.targeting.$targetId'
import { Route as SmartopsProposalsProposalIdRouteImport } from './routes/smartops.proposals.$proposalId'
import { Route as SmartopsConductSessionIdRouteImport } from './routes/smartops.conduct.$sessionId'
import { Route as SmartopsBdaCreateRouteImport } from './routes/smartops.bda.create'
import { Route as SmartopsBdaReportIdRouteImport } from './routes/smartops.bda.$reportId'
import { Route as AdminDiscoveryServiceIdRouteImport } from './routes/admin/discovery/$serviceId'

const SmartopsOplanLazyRouteImport = createFileRoute('/smartops/oplan')()

const SmartopsRoute = SmartopsRouteImport.update({
  id: '/smartops',
  path: '/smartops',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugRoute = DebugRouteImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiManagementRoute = ApiManagementRouteImport.update({
  id: '/api-management',
  path: '/api-management',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SmartopsIndexRoute = SmartopsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SmartopsRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SmartopsOplanLazyRoute = SmartopsOplanLazyRouteImport.update({
  id: '/oplan',
  path: '/oplan',
  getParentRoute: () => SmartopsRoute,
} as any).lazy(() =>
  import('./routes/smartops.oplan.lazy').then((d) => d.Route),
)
const StatsUsersRoute = StatsUsersRouteImport.update({
  id: '/stats/users',
  path: '/stats/users',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsSystemRoute = StatsSystemRouteImport.update({
  id: '/stats/system',
  path: '/stats/system',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsSessionsRoute = StatsSessionsRouteImport.update({
  id: '/stats/sessions',
  path: '/stats/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const SmartopsWeatherRoute = SmartopsWeatherRouteImport.update({
  id: '/weather',
  path: '/weather',
  getParentRoute: () => SmartopsRoute,
} as any)
const SmartopsUncertaintyRoute = SmartopsUncertaintyRouteImport.update({
  id: '/uncertainty',
  path: '/uncertainty',
  getParentRoute: () => SmartopsRoute,
} as any)
const SmartopsTriageRoute = SmartopsTriageRouteImport.update({
  id: '/triage',
  path: '/triage',
  getParentRoute: () => SmartopsRoute,
} as any).lazy(() =>
  import('./routes/smartops.triage.lazy').then((d) => d.Route),
)
const SmartopsTorManagerRoute = SmartopsTorManagerRouteImport.update({
  id: '/tor-manager',
  path: '/tor-manager',
  getParentRoute: () => SmartopsRoute,
} as any)
const SmartopsTargetingCellDashboardRoute =
  SmartopsTargetingCellDashboardRouteImport.update({
    id: '/targeting-cell-dashboard',
    path: '/targeting-cell-dashboard',
    getParentRoute: () => SmartopsRoute,
  } as any)
const SmartopsSupplyChainRoute = SmartopsSupplyChainRouteImport.update({
  id: '/supply-chain',
  path: '/supply-chain',
  getParentRoute: () => SmartopsRoute,
} as any)
const SmartopsStrikeOptimizerRoute = SmartopsStrikeOptimizerRouteImport.update({
  id: '/strike-optimizer',
  path: '/strike-optimizer',
  getParentRoute: () => SmartopsRoute,
} as any)
const SmartopsStrategicDirectionRoute =
  SmartopsStrategicDirectionRouteImport.update({
    id: '/strategic-direction',
    path: '/strategic-direction',
    getParentRoute: () => SmartopsRoute,
  } as any)
const SmartopsStaffRoute = SmartopsStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => SmartopsRoute,
} as any)
const SmartopsSocialDomainRoute = SmartopsSocialDomainRouteImport.update({
  id: '/social-domain',
  path: '/social-domain',
  getParentRoute: () => SmartopsRoute,
} as any)
const SmartopsSecurityRoute = SmartopsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => SmartopsRoute,
} as any)
const SmartopsScenariosRoute = SmartopsScenariosRouteImport.update({
  id: '/scenarios',
  path: '/scenarios',
  getParentRoute: () => SmartopsRoute,
} as any)
const SmartopsRxpRoute = SmartopsRxpRouteImport.update({
  id: '/rxp',
  path: '/rxp',
  getParentRoute: () => SmartopsRoute,
} as any)
const SmartopsRoeRoute = SmartopsRoeRouteImport.update({
  id: '/roe',
  path: '/roe',
  getParentRoute: () => SmartopsRoute,
} as any)
const SmartopsRfisRoute = SmartopsRfisRouteImport.update({
  id: '/rfis',
  path: '/rfis',
  getParentRoute: () => SmartopsRoute,
} as any)
const SmartopsProductsRoute = SmartopsProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => SmartopsRoute,
} as any)
const SmartopsPersonnelRoute = SmartopsPersonnelRouteImport.update({
  id: '/personnel',
  path: '/personnel',
  getParentRoute: () => SmartopsRoute,
} as any)
const SmartopsOrbatRoute = SmartopsOrbatRouteImport.update({
  id: '/orbat',
  path: '/orbat',
  getParentRoute: () => SmartopsRoute,
} as any)
const SmartopsOntologyRoute = SmartopsOntologyRouteImport.update({
  id: '/ontology',
  path: '/ontology',
  getParentRoute: () => SmartopsRoute,
} as any)
const SmartopsMenuBuilderRoute = SmartopsMenuBuilderRouteImport.update({
  id: '/menu-builder',
  path: '/menu-builder',
  getParentRoute: () => SmartopsRoute,
} as any)
const SmartopsMdoRoute = SmartopsMdoRouteImport.update({
  id: '/mdo',
  path: '/mdo',
  getParentRoute: () => SmartopsRoute,
} as any)
const SmartopsLogisticsRoute = SmartopsLogisticsRouteImport.update({
  id: '/logistics',
  path: '/logistics',
  getParentRoute: () => SmartopsRoute,
} as any)
const SmartopsLegadDashboardRoute = SmartopsLegadDashboardRouteImport.update({
  id: '/legad-dashboard',
  path: '/legad-dashboard',
  getParentRoute: () => SmartopsRoute,
} as any)
const SmartopsJ5DashboardRoute = SmartopsJ5DashboardRouteImport.update({
  id: '/j5-dashboard',
  path: '/j5-dashboard',
  getParentRoute: () => SmartopsRoute,
} as any)
const SmartopsJ4DashboardRoute = SmartopsJ4DashboardRouteImport.update({
  id: '/j4-dashboard',
  path: '/j4-dashboard',
  getParentRoute: () => SmartopsRoute,
} as any)
const SmartopsJ3DashboardRoute = SmartopsJ3DashboardRouteImport.update({
  id: '/j3-dashboard',
  path: '/j3-dashboard',
  getParentRoute: () => SmartopsRoute,
} as any)
const SmartopsJ2DashboardRoute = SmartopsJ2DashboardRouteImport.update({
  id: '/j2-dashboard',
  path: '/j2-dashboard',
  getParentRoute: () => SmartopsRoute,
} as any)
const SmartopsInfrastructureRoute = SmartopsInfrastructureRouteImport.update({
  id: '/infrastructure',
  path: '/infrastructure',
  getParentRoute: () => SmartopsRoute,
} as any)
const SmartopsInformationManagementRoute =
  SmartopsInformationManagementRouteImport.update({
    id: '/information-management',
    path: '/information-management',
    getParentRoute: () => SmartopsRoute,
  } as any)
const SmartopsImDashboardRoute = SmartopsImDashboardRouteImport.update({
  id: '/im-dashboard',
  path: '/im-dashboard',
  getParentRoute: () => SmartopsRoute,
} as any)
const SmartopsGapAnalysisRoute = SmartopsGapAnalysisRouteImport.update({
  id: '/gap-analysis',
  path: '/gap-analysis',
  getParentRoute: () => SmartopsRoute,
} as any).lazy(() =>
  import('./routes/smartops.gap-analysis.lazy').then((d) => d.Route),
)
const SmartopsFeedbackRoute = SmartopsFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => SmartopsRoute,
} as any)
const SmartopsExternalContextRoute = SmartopsExternalContextRouteImport.update({
  id: '/external-context',
  path: '/external-context',
  getParentRoute: () => SmartopsRoute,
} as any)
const SmartopsDigitalTwinRoute = SmartopsDigitalTwinRouteImport.update({
  id: '/digital-twin',
  path: '/digital-twin',
  getParentRoute: () => SmartopsRoute,
} as any).lazy(() =>
  import('./routes/smartops.digital-twin.lazy').then((d) => d.Route),
)
const SmartopsDecisionBoardRoute = SmartopsDecisionBoardRouteImport.update({
  id: '/decision-board',
  path: '/decision-board',
  getParentRoute: () => SmartopsRoute,
} as any)
const SmartopsCopSummaryRoute = SmartopsCopSummaryRouteImport.update({
  id: '/cop-summary',
  path: '/cop-summary',
  getParentRoute: () => SmartopsRoute,
} as any)
const SmartopsConopsRoute = SmartopsConopsRouteImport.update({
  id: '/conops',
  path: '/conops',
  getParentRoute: () => SmartopsRoute,
} as any)
const SmartopsCogRoute = SmartopsCogRouteImport.update({
  id: '/cog',
  path: '/cog',
  getParentRoute: () => SmartopsRoute,
} as any)
const SmartopsCoaWargamerRoute = SmartopsCoaWargamerRouteImport.update({
  id: '/coa-wargamer',
  path: '/coa-wargamer',
  getParentRoute: () => SmartopsRoute,
} as any)
const SmartopsCnrRoute = SmartopsCnrRouteImport.update({
  id: '/cnr',
  path: '/cnr',
  getParentRoute: () => SmartopsRoute,
} as any)
const SmartopsCdeRoute = SmartopsCdeRouteImport.update({
  id: '/cde',
  path: '/cde',
  getParentRoute: () => SmartopsRoute,
} as any)
const SmartopsCcirRoute = SmartopsCcirRouteImport.update({
  id: '/ccir',
  path: '/ccir',
  getParentRoute: () => SmartopsRoute,
} as any)
const SmartopsCampaignRoute = SmartopsCampaignRouteImport.update({
  id: '/campaign',
  path: '/campaign',
  getParentRoute: () => SmartopsRoute,
} as any)
const SmartopsBriefingRoute = SmartopsBriefingRouteImport.update({
  id: '/briefing',
  path: '/briefing',
  getParentRoute: () => SmartopsRoute,
} as any)
const SmartopsBrainstormingRoute = SmartopsBrainstormingRouteImport.update({
  id: '/brainstorming',
  path: '/brainstorming',
  getParentRoute: () => SmartopsRoute,
} as any)
const SmartopsBdaRoute = SmartopsBdaRouteImport.update({
  id: '/bda',
  path: '/bda',
  getParentRoute: () => SmartopsRoute,
} as any)
const SmartopsBattleRhythmRoute = SmartopsBattleRhythmRouteImport.update({
  id: '/battle-rhythm',
  path: '/battle-rhythm',
  getParentRoute: () => SmartopsRoute,
} as any).lazy(() =>
  import('./routes/smartops.battle-rhythm.lazy').then((d) => d.Route),
)
const SmartopsAssumptionsRoute = SmartopsAssumptionsRouteImport.update({
  id: '/assumptions',
  path: '/assumptions',
  getParentRoute: () => SmartopsRoute,
} as any)
const SmartopsAssessmentRoute = SmartopsAssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => SmartopsRoute,
} as any)
const SmartopsAnalystDashboardRoute =
  SmartopsAnalystDashboardRouteImport.update({
    id: '/analyst-dashboard',
    path: '/analyst-dashboard',
    getParentRoute: () => SmartopsRoute,
  } as any)
const SmartopsAdvisoryRoute = SmartopsAdvisoryRouteImport.update({
  id: '/advisory',
  path: '/advisory',
  getParentRoute: () => SmartopsRoute,
} as any).lazy(() =>
  import('./routes/smartops.advisory.lazy').then((d) => d.Route),
)
const SmartopsA2adRoute = SmartopsA2adRouteImport.update({
  id: '/a2ad',
  path: '/a2ad',
  getParentRoute: () => SmartopsRoute,
} as any).lazy(() => import('./routes/smartops.a2ad.lazy').then((d) => d.Route))
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRateLimitsRoute = AdminRateLimitsRouteImport.update({
  id: '/rate-limits',
  path: '/rate-limits',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNewRoute = AdminNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDiscoveryRoute = AdminDiscoveryRouteImport.update({
  id: '/discovery',
  path: '/discovery',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAbacRoute = AdminAbacRouteImport.update({
  id: '/abac',
  path: '/abac',
  getParentRoute: () => AdminRoute,
} as any)
const SmartopsTargetingIndexRoute = SmartopsTargetingIndexRouteImport.update({
  id: '/targeting/',
  path: '/targeting/',
  getParentRoute: () => SmartopsRoute,
} as any)
const SmartopsProposalsIndexRoute = SmartopsProposalsIndexRouteImport.update({
  id: '/proposals/',
  path: '/proposals/',
  getParentRoute: () => SmartopsRoute,
} as any)
const AdminDiscoveryIndexRoute = AdminDiscoveryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminDiscoveryRoute,
} as any)
const SmartopsTargetingTargetsRoute =
  SmartopsTargetingTargetsRouteImport.update({
    id: '/targeting/targets',
    path: '/targeting/targets',
    getParentRoute: () => SmartopsRoute,
  } as any)
const SmartopsTargetingRiskRoute = SmartopsTargetingRiskRouteImport.update({
  id: '/targeting/risk',
  path: '/targeting/risk',
  getParentRoute: () => SmartopsRoute,
} as any)
const SmartopsTargetingNominateRoute =
  SmartopsTargetingNominateRouteImport.update({
    id: '/targeting/nominate',
    path: '/targeting/nominate',
    getParentRoute: () => SmartopsRoute,
  } as any)
const SmartopsTargetingMissionCommandRoute =
  SmartopsTargetingMissionCommandRouteImport.update({
    id: '/targeting/mission-command',
    path: '/targeting/mission-command',
    getParentRoute: () => SmartopsRoute,
  } as any)
const SmartopsTargetingJtbRoute = SmartopsTargetingJtbRouteImport.update({
  id: '/targeting/jtb',
  path: '/targeting/jtb',
  getParentRoute: () => SmartopsRoute,
} as any)
const SmartopsTargetingIntelligenceRoute =
  SmartopsTargetingIntelligenceRouteImport.update({
    id: '/targeting/intelligence',
    path: '/targeting/intelligence',
    getParentRoute: () => SmartopsRoute,
  } as any)
const SmartopsTargetingEmergencyRoute =
  SmartopsTargetingEmergencyRouteImport.update({
    id: '/targeting/emergency',
    path: '/targeting/emergency',
    getParentRoute: () => SmartopsRoute,
  } as any)
const SmartopsTargetingEffectsRoute =
  SmartopsTargetingEffectsRouteImport.update({
    id: '/targeting/effects',
    path: '/targeting/effects',
    getParentRoute: () => SmartopsRoute,
  } as any)
const SmartopsTargetingCollaborationRoute =
  SmartopsTargetingCollaborationRouteImport.update({
    id: '/targeting/collaboration',
    path: '/targeting/collaboration',
    getParentRoute: () => SmartopsRoute,
  } as any)
const SmartopsTargetingAssetsRoute = SmartopsTargetingAssetsRouteImport.update({
  id: '/targeting/assets',
  path: '/targeting/assets',
  getParentRoute: () => SmartopsRoute,
} as any)
const SmartopsTargetingAnalyticsRoute =
  SmartopsTargetingAnalyticsRouteImport.update({
    id: '/targeting/analytics',
    path: '/targeting/analytics',
    getParentRoute: () => SmartopsRoute,
  } as any)
const SmartopsTargetingAnalysisRoute =
  SmartopsTargetingAnalysisRouteImport.update({
    id: '/targeting/analysis',
    path: '/targeting/analysis',
    getParentRoute: () => SmartopsRoute,
  } as any)
const SmartopsTargetingTargetIdRoute =
  SmartopsTargetingTargetIdRouteImport.update({
    id: '/targeting/$targetId',
    path: '/targeting/$targetId',
    getParentRoute: () => SmartopsRoute,
  } as any)
const SmartopsProposalsProposalIdRoute =
  SmartopsProposalsProposalIdRouteImport.update({
    id: '/proposals/$proposalId',
    path: '/proposals/$proposalId',
    getParentRoute: () => SmartopsRoute,
  } as any)
const SmartopsConductSessionIdRoute =
  SmartopsConductSessionIdRouteImport.update({
    id: '/conduct/$sessionId',
    path: '/conduct/$sessionId',
    getParentRoute: () => SmartopsRoute,
  } as any).lazy(() =>
    import('./routes/smartops.conduct.$sessionId.lazy').then((d) => d.Route),
  )
const SmartopsBdaCreateRoute = SmartopsBdaCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => SmartopsBdaRoute,
} as any)
const SmartopsBdaReportIdRoute = SmartopsBdaReportIdRouteImport.update({
  id: '/$reportId',
  path: '/$reportId',
  getParentRoute: () => SmartopsBdaRoute,
} as any)
const AdminDiscoveryServiceIdRoute = AdminDiscoveryServiceIdRouteImport.update({
  id: '/$serviceId',
  path: '/$serviceId',
  getParentRoute: () => AdminDiscoveryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/api-management': typeof ApiManagementRoute
  '/debug': typeof DebugRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/smartops': typeof SmartopsRouteWithChildren
  '/admin/abac': typeof AdminAbacRoute
  '/admin/discovery': typeof AdminDiscoveryRouteWithChildren
  '/admin/new': typeof AdminNewRoute
  '/admin/rate-limits': typeof AdminRateLimitsRoute
  '/admin/users': typeof AdminUsersRoute
  '/smartops/a2ad': typeof SmartopsA2adRoute
  '/smartops/advisory': typeof SmartopsAdvisoryRoute
  '/smartops/analyst-dashboard': typeof SmartopsAnalystDashboardRoute
  '/smartops/assessment': typeof SmartopsAssessmentRoute
  '/smartops/assumptions': typeof SmartopsAssumptionsRoute
  '/smartops/battle-rhythm': typeof SmartopsBattleRhythmRoute
  '/smartops/bda': typeof SmartopsBdaRouteWithChildren
  '/smartops/brainstorming': typeof SmartopsBrainstormingRoute
  '/smartops/briefing': typeof SmartopsBriefingRoute
  '/smartops/campaign': typeof SmartopsCampaignRoute
  '/smartops/ccir': typeof SmartopsCcirRoute
  '/smartops/cde': typeof SmartopsCdeRoute
  '/smartops/cnr': typeof SmartopsCnrRoute
  '/smartops/coa-wargamer': typeof SmartopsCoaWargamerRoute
  '/smartops/cog': typeof SmartopsCogRoute
  '/smartops/conops': typeof SmartopsConopsRoute
  '/smartops/cop-summary': typeof SmartopsCopSummaryRoute
  '/smartops/decision-board': typeof SmartopsDecisionBoardRoute
  '/smartops/digital-twin': typeof SmartopsDigitalTwinRoute
  '/smartops/external-context': typeof SmartopsExternalContextRoute
  '/smartops/feedback': typeof SmartopsFeedbackRoute
  '/smartops/gap-analysis': typeof SmartopsGapAnalysisRoute
  '/smartops/im-dashboard': typeof SmartopsImDashboardRoute
  '/smartops/information-management': typeof SmartopsInformationManagementRoute
  '/smartops/infrastructure': typeof SmartopsInfrastructureRoute
  '/smartops/j2-dashboard': typeof SmartopsJ2DashboardRoute
  '/smartops/j3-dashboard': typeof SmartopsJ3DashboardRoute
  '/smartops/j4-dashboard': typeof SmartopsJ4DashboardRoute
  '/smartops/j5-dashboard': typeof SmartopsJ5DashboardRoute
  '/smartops/legad-dashboard': typeof SmartopsLegadDashboardRoute
  '/smartops/logistics': typeof SmartopsLogisticsRoute
  '/smartops/mdo': typeof SmartopsMdoRoute
  '/smartops/menu-builder': typeof SmartopsMenuBuilderRoute
  '/smartops/ontology': typeof SmartopsOntologyRoute
  '/smartops/orbat': typeof SmartopsOrbatRoute
  '/smartops/personnel': typeof SmartopsPersonnelRoute
  '/smartops/products': typeof SmartopsProductsRoute
  '/smartops/rfis': typeof SmartopsRfisRoute
  '/smartops/roe': typeof SmartopsRoeRoute
  '/smartops/rxp': typeof SmartopsRxpRoute
  '/smartops/scenarios': typeof SmartopsScenariosRoute
  '/smartops/security': typeof SmartopsSecurityRoute
  '/smartops/social-domain': typeof SmartopsSocialDomainRoute
  '/smartops/staff': typeof SmartopsStaffRoute
  '/smartops/strategic-direction': typeof SmartopsStrategicDirectionRoute
  '/smartops/strike-optimizer': typeof SmartopsStrikeOptimizerRoute
  '/smartops/supply-chain': typeof SmartopsSupplyChainRoute
  '/smartops/targeting-cell-dashboard': typeof SmartopsTargetingCellDashboardRoute
  '/smartops/tor-manager': typeof SmartopsTorManagerRoute
  '/smartops/triage': typeof SmartopsTriageRoute
  '/smartops/uncertainty': typeof SmartopsUncertaintyRoute
  '/smartops/weather': typeof SmartopsWeatherRoute
  '/stats/sessions': typeof StatsSessionsRoute
  '/stats/system': typeof StatsSystemRoute
  '/stats/users': typeof StatsUsersRoute
  '/smartops/oplan': typeof SmartopsOplanLazyRoute
  '/admin/': typeof AdminIndexRoute
  '/smartops/': typeof SmartopsIndexRoute
  '/admin/discovery/$serviceId': typeof AdminDiscoveryServiceIdRoute
  '/smartops/bda/$reportId': typeof SmartopsBdaReportIdRoute
  '/smartops/bda/create': typeof SmartopsBdaCreateRoute
  '/smartops/conduct/$sessionId': typeof SmartopsConductSessionIdRoute
  '/smartops/proposals/$proposalId': typeof SmartopsProposalsProposalIdRoute
  '/smartops/targeting/$targetId': typeof SmartopsTargetingTargetIdRoute
  '/smartops/targeting/analysis': typeof SmartopsTargetingAnalysisRoute
  '/smartops/targeting/analytics': typeof SmartopsTargetingAnalyticsRoute
  '/smartops/targeting/assets': typeof SmartopsTargetingAssetsRoute
  '/smartops/targeting/collaboration': typeof SmartopsTargetingCollaborationRoute
  '/smartops/targeting/effects': typeof SmartopsTargetingEffectsRoute
  '/smartops/targeting/emergency': typeof SmartopsTargetingEmergencyRoute
  '/smartops/targeting/intelligence': typeof SmartopsTargetingIntelligenceRoute
  '/smartops/targeting/jtb': typeof SmartopsTargetingJtbRoute
  '/smartops/targeting/mission-command': typeof SmartopsTargetingMissionCommandRoute
  '/smartops/targeting/nominate': typeof SmartopsTargetingNominateRoute
  '/smartops/targeting/risk': typeof SmartopsTargetingRiskRoute
  '/smartops/targeting/targets': typeof SmartopsTargetingTargetsRoute
  '/admin/discovery/': typeof AdminDiscoveryIndexRoute
  '/smartops/proposals': typeof SmartopsProposalsIndexRoute
  '/smartops/targeting': typeof SmartopsTargetingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api-management': typeof ApiManagementRoute
  '/debug': typeof DebugRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/admin/abac': typeof AdminAbacRoute
  '/admin/new': typeof AdminNewRoute
  '/admin/rate-limits': typeof AdminRateLimitsRoute
  '/admin/users': typeof AdminUsersRoute
  '/smartops/a2ad': typeof SmartopsA2adRoute
  '/smartops/advisory': typeof SmartopsAdvisoryRoute
  '/smartops/analyst-dashboard': typeof SmartopsAnalystDashboardRoute
  '/smartops/assessment': typeof SmartopsAssessmentRoute
  '/smartops/assumptions': typeof SmartopsAssumptionsRoute
  '/smartops/battle-rhythm': typeof SmartopsBattleRhythmRoute
  '/smartops/bda': typeof SmartopsBdaRouteWithChildren
  '/smartops/brainstorming': typeof SmartopsBrainstormingRoute
  '/smartops/briefing': typeof SmartopsBriefingRoute
  '/smartops/campaign': typeof SmartopsCampaignRoute
  '/smartops/ccir': typeof SmartopsCcirRoute
  '/smartops/cde': typeof SmartopsCdeRoute
  '/smartops/cnr': typeof SmartopsCnrRoute
  '/smartops/coa-wargamer': typeof SmartopsCoaWargamerRoute
  '/smartops/cog': typeof SmartopsCogRoute
  '/smartops/conops': typeof SmartopsConopsRoute
  '/smartops/cop-summary': typeof SmartopsCopSummaryRoute
  '/smartops/decision-board': typeof SmartopsDecisionBoardRoute
  '/smartops/digital-twin': typeof SmartopsDigitalTwinRoute
  '/smartops/external-context': typeof SmartopsExternalContextRoute
  '/smartops/feedback': typeof SmartopsFeedbackRoute
  '/smartops/gap-analysis': typeof SmartopsGapAnalysisRoute
  '/smartops/im-dashboard': typeof SmartopsImDashboardRoute
  '/smartops/information-management': typeof SmartopsInformationManagementRoute
  '/smartops/infrastructure': typeof SmartopsInfrastructureRoute
  '/smartops/j2-dashboard': typeof SmartopsJ2DashboardRoute
  '/smartops/j3-dashboard': typeof SmartopsJ3DashboardRoute
  '/smartops/j4-dashboard': typeof SmartopsJ4DashboardRoute
  '/smartops/j5-dashboard': typeof SmartopsJ5DashboardRoute
  '/smartops/legad-dashboard': typeof SmartopsLegadDashboardRoute
  '/smartops/logistics': typeof SmartopsLogisticsRoute
  '/smartops/mdo': typeof SmartopsMdoRoute
  '/smartops/menu-builder': typeof SmartopsMenuBuilderRoute
  '/smartops/ontology': typeof SmartopsOntologyRoute
  '/smartops/orbat': typeof SmartopsOrbatRoute
  '/smartops/personnel': typeof SmartopsPersonnelRoute
  '/smartops/products': typeof SmartopsProductsRoute
  '/smartops/rfis': typeof SmartopsRfisRoute
  '/smartops/roe': typeof SmartopsRoeRoute
  '/smartops/rxp': typeof SmartopsRxpRoute
  '/smartops/scenarios': typeof SmartopsScenariosRoute
  '/smartops/security': typeof SmartopsSecurityRoute
  '/smartops/social-domain': typeof SmartopsSocialDomainRoute
  '/smartops/staff': typeof SmartopsStaffRoute
  '/smartops/strategic-direction': typeof SmartopsStrategicDirectionRoute
  '/smartops/strike-optimizer': typeof SmartopsStrikeOptimizerRoute
  '/smartops/supply-chain': typeof SmartopsSupplyChainRoute
  '/smartops/targeting-cell-dashboard': typeof SmartopsTargetingCellDashboardRoute
  '/smartops/tor-manager': typeof SmartopsTorManagerRoute
  '/smartops/triage': typeof SmartopsTriageRoute
  '/smartops/uncertainty': typeof SmartopsUncertaintyRoute
  '/smartops/weather': typeof SmartopsWeatherRoute
  '/stats/sessions': typeof StatsSessionsRoute
  '/stats/system': typeof StatsSystemRoute
  '/stats/users': typeof StatsUsersRoute
  '/smartops/oplan': typeof SmartopsOplanLazyRoute
  '/admin': typeof AdminIndexRoute
  '/smartops': typeof SmartopsIndexRoute
  '/admin/discovery/$serviceId': typeof AdminDiscoveryServiceIdRoute
  '/smartops/bda/$reportId': typeof SmartopsBdaReportIdRoute
  '/smartops/bda/create': typeof SmartopsBdaCreateRoute
  '/smartops/conduct/$sessionId': typeof SmartopsConductSessionIdRoute
  '/smartops/proposals/$proposalId': typeof SmartopsProposalsProposalIdRoute
  '/smartops/targeting/$targetId': typeof SmartopsTargetingTargetIdRoute
  '/smartops/targeting/analysis': typeof SmartopsTargetingAnalysisRoute
  '/smartops/targeting/analytics': typeof SmartopsTargetingAnalyticsRoute
  '/smartops/targeting/assets': typeof SmartopsTargetingAssetsRoute
  '/smartops/targeting/collaboration': typeof SmartopsTargetingCollaborationRoute
  '/smartops/targeting/effects': typeof SmartopsTargetingEffectsRoute
  '/smartops/targeting/emergency': typeof SmartopsTargetingEmergencyRoute
  '/smartops/targeting/intelligence': typeof SmartopsTargetingIntelligenceRoute
  '/smartops/targeting/jtb': typeof SmartopsTargetingJtbRoute
  '/smartops/targeting/mission-command': typeof SmartopsTargetingMissionCommandRoute
  '/smartops/targeting/nominate': typeof SmartopsTargetingNominateRoute
  '/smartops/targeting/risk': typeof SmartopsTargetingRiskRoute
  '/smartops/targeting/targets': typeof SmartopsTargetingTargetsRoute
  '/admin/discovery': typeof AdminDiscoveryIndexRoute
  '/smartops/proposals': typeof SmartopsProposalsIndexRoute
  '/smartops/targeting': typeof SmartopsTargetingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/api-management': typeof ApiManagementRoute
  '/debug': typeof DebugRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/smartops': typeof SmartopsRouteWithChildren
  '/admin/abac': typeof AdminAbacRoute
  '/admin/discovery': typeof AdminDiscoveryRouteWithChildren
  '/admin/new': typeof AdminNewRoute
  '/admin/rate-limits': typeof AdminRateLimitsRoute
  '/admin/users': typeof AdminUsersRoute
  '/smartops/a2ad': typeof SmartopsA2adRoute
  '/smartops/advisory': typeof SmartopsAdvisoryRoute
  '/smartops/analyst-dashboard': typeof SmartopsAnalystDashboardRoute
  '/smartops/assessment': typeof SmartopsAssessmentRoute
  '/smartops/assumptions': typeof SmartopsAssumptionsRoute
  '/smartops/battle-rhythm': typeof SmartopsBattleRhythmRoute
  '/smartops/bda': typeof SmartopsBdaRouteWithChildren
  '/smartops/brainstorming': typeof SmartopsBrainstormingRoute
  '/smartops/briefing': typeof SmartopsBriefingRoute
  '/smartops/campaign': typeof SmartopsCampaignRoute
  '/smartops/ccir': typeof SmartopsCcirRoute
  '/smartops/cde': typeof SmartopsCdeRoute
  '/smartops/cnr': typeof SmartopsCnrRoute
  '/smartops/coa-wargamer': typeof SmartopsCoaWargamerRoute
  '/smartops/cog': typeof SmartopsCogRoute
  '/smartops/conops': typeof SmartopsConopsRoute
  '/smartops/cop-summary': typeof SmartopsCopSummaryRoute
  '/smartops/decision-board': typeof SmartopsDecisionBoardRoute
  '/smartops/digital-twin': typeof SmartopsDigitalTwinRoute
  '/smartops/external-context': typeof SmartopsExternalContextRoute
  '/smartops/feedback': typeof SmartopsFeedbackRoute
  '/smartops/gap-analysis': typeof SmartopsGapAnalysisRoute
  '/smartops/im-dashboard': typeof SmartopsImDashboardRoute
  '/smartops/information-management': typeof SmartopsInformationManagementRoute
  '/smartops/infrastructure': typeof SmartopsInfrastructureRoute
  '/smartops/j2-dashboard': typeof SmartopsJ2DashboardRoute
  '/smartops/j3-dashboard': typeof SmartopsJ3DashboardRoute
  '/smartops/j4-dashboard': typeof SmartopsJ4DashboardRoute
  '/smartops/j5-dashboard': typeof SmartopsJ5DashboardRoute
  '/smartops/legad-dashboard': typeof SmartopsLegadDashboardRoute
  '/smartops/logistics': typeof SmartopsLogisticsRoute
  '/smartops/mdo': typeof SmartopsMdoRoute
  '/smartops/menu-builder': typeof SmartopsMenuBuilderRoute
  '/smartops/ontology': typeof SmartopsOntologyRoute
  '/smartops/orbat': typeof SmartopsOrbatRoute
  '/smartops/personnel': typeof SmartopsPersonnelRoute
  '/smartops/products': typeof SmartopsProductsRoute
  '/smartops/rfis': typeof SmartopsRfisRoute
  '/smartops/roe': typeof SmartopsRoeRoute
  '/smartops/rxp': typeof SmartopsRxpRoute
  '/smartops/scenarios': typeof SmartopsScenariosRoute
  '/smartops/security': typeof SmartopsSecurityRoute
  '/smartops/social-domain': typeof SmartopsSocialDomainRoute
  '/smartops/staff': typeof SmartopsStaffRoute
  '/smartops/strategic-direction': typeof SmartopsStrategicDirectionRoute
  '/smartops/strike-optimizer': typeof SmartopsStrikeOptimizerRoute
  '/smartops/supply-chain': typeof SmartopsSupplyChainRoute
  '/smartops/targeting-cell-dashboard': typeof SmartopsTargetingCellDashboardRoute
  '/smartops/tor-manager': typeof SmartopsTorManagerRoute
  '/smartops/triage': typeof SmartopsTriageRoute
  '/smartops/uncertainty': typeof SmartopsUncertaintyRoute
  '/smartops/weather': typeof SmartopsWeatherRoute
  '/stats/sessions': typeof StatsSessionsRoute
  '/stats/system': typeof StatsSystemRoute
  '/stats/users': typeof StatsUsersRoute
  '/smartops/oplan': typeof SmartopsOplanLazyRoute
  '/admin/': typeof AdminIndexRoute
  '/smartops/': typeof SmartopsIndexRoute
  '/admin/discovery/$serviceId': typeof AdminDiscoveryServiceIdRoute
  '/smartops/bda/$reportId': typeof SmartopsBdaReportIdRoute
  '/smartops/bda/create': typeof SmartopsBdaCreateRoute
  '/smartops/conduct/$sessionId': typeof SmartopsConductSessionIdRoute
  '/smartops/proposals/$proposalId': typeof SmartopsProposalsProposalIdRoute
  '/smartops/targeting/$targetId': typeof SmartopsTargetingTargetIdRoute
  '/smartops/targeting/analysis': typeof SmartopsTargetingAnalysisRoute
  '/smartops/targeting/analytics': typeof SmartopsTargetingAnalyticsRoute
  '/smartops/targeting/assets': typeof SmartopsTargetingAssetsRoute
  '/smartops/targeting/collaboration': typeof SmartopsTargetingCollaborationRoute
  '/smartops/targeting/effects': typeof SmartopsTargetingEffectsRoute
  '/smartops/targeting/emergency': typeof SmartopsTargetingEmergencyRoute
  '/smartops/targeting/intelligence': typeof SmartopsTargetingIntelligenceRoute
  '/smartops/targeting/jtb': typeof SmartopsTargetingJtbRoute
  '/smartops/targeting/mission-command': typeof SmartopsTargetingMissionCommandRoute
  '/smartops/targeting/nominate': typeof SmartopsTargetingNominateRoute
  '/smartops/targeting/risk': typeof SmartopsTargetingRiskRoute
  '/smartops/targeting/targets': typeof SmartopsTargetingTargetsRoute
  '/admin/discovery/': typeof AdminDiscoveryIndexRoute
  '/smartops/proposals/': typeof SmartopsProposalsIndexRoute
  '/smartops/targeting/': typeof SmartopsTargetingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/api-management'
    | '/debug'
    | '/login'
    | '/logs'
    | '/profile'
    | '/register'
    | '/reports'
    | '/smartops'
    | '/admin/abac'
    | '/admin/discovery'
    | '/admin/new'
    | '/admin/rate-limits'
    | '/admin/users'
    | '/smartops/a2ad'
    | '/smartops/advisory'
    | '/smartops/analyst-dashboard'
    | '/smartops/assessment'
    | '/smartops/assumptions'
    | '/smartops/battle-rhythm'
    | '/smartops/bda'
    | '/smartops/brainstorming'
    | '/smartops/briefing'
    | '/smartops/campaign'
    | '/smartops/ccir'
    | '/smartops/cde'
    | '/smartops/cnr'
    | '/smartops/coa-wargamer'
    | '/smartops/cog'
    | '/smartops/conops'
    | '/smartops/cop-summary'
    | '/smartops/decision-board'
    | '/smartops/digital-twin'
    | '/smartops/external-context'
    | '/smartops/feedback'
    | '/smartops/gap-analysis'
    | '/smartops/im-dashboard'
    | '/smartops/information-management'
    | '/smartops/infrastructure'
    | '/smartops/j2-dashboard'
    | '/smartops/j3-dashboard'
    | '/smartops/j4-dashboard'
    | '/smartops/j5-dashboard'
    | '/smartops/legad-dashboard'
    | '/smartops/logistics'
    | '/smartops/mdo'
    | '/smartops/menu-builder'
    | '/smartops/ontology'
    | '/smartops/orbat'
    | '/smartops/personnel'
    | '/smartops/products'
    | '/smartops/rfis'
    | '/smartops/roe'
    | '/smartops/rxp'
    | '/smartops/scenarios'
    | '/smartops/security'
    | '/smartops/social-domain'
    | '/smartops/staff'
    | '/smartops/strategic-direction'
    | '/smartops/strike-optimizer'
    | '/smartops/supply-chain'
    | '/smartops/targeting-cell-dashboard'
    | '/smartops/tor-manager'
    | '/smartops/triage'
    | '/smartops/uncertainty'
    | '/smartops/weather'
    | '/stats/sessions'
    | '/stats/system'
    | '/stats/users'
    | '/smartops/oplan'
    | '/admin/'
    | '/smartops/'
    | '/admin/discovery/$serviceId'
    | '/smartops/bda/$reportId'
    | '/smartops/bda/create'
    | '/smartops/conduct/$sessionId'
    | '/smartops/proposals/$proposalId'
    | '/smartops/targeting/$targetId'
    | '/smartops/targeting/analysis'
    | '/smartops/targeting/analytics'
    | '/smartops/targeting/assets'
    | '/smartops/targeting/collaboration'
    | '/smartops/targeting/effects'
    | '/smartops/targeting/emergency'
    | '/smartops/targeting/intelligence'
    | '/smartops/targeting/jtb'
    | '/smartops/targeting/mission-command'
    | '/smartops/targeting/nominate'
    | '/smartops/targeting/risk'
    | '/smartops/targeting/targets'
    | '/admin/discovery/'
    | '/smartops/proposals'
    | '/smartops/targeting'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api-management'
    | '/debug'
    | '/login'
    | '/logs'
    | '/profile'
    | '/register'
    | '/reports'
    | '/admin/abac'
    | '/admin/new'
    | '/admin/rate-limits'
    | '/admin/users'
    | '/smartops/a2ad'
    | '/smartops/advisory'
    | '/smartops/analyst-dashboard'
    | '/smartops/assessment'
    | '/smartops/assumptions'
    | '/smartops/battle-rhythm'
    | '/smartops/bda'
    | '/smartops/brainstorming'
    | '/smartops/briefing'
    | '/smartops/campaign'
    | '/smartops/ccir'
    | '/smartops/cde'
    | '/smartops/cnr'
    | '/smartops/coa-wargamer'
    | '/smartops/cog'
    | '/smartops/conops'
    | '/smartops/cop-summary'
    | '/smartops/decision-board'
    | '/smartops/digital-twin'
    | '/smartops/external-context'
    | '/smartops/feedback'
    | '/smartops/gap-analysis'
    | '/smartops/im-dashboard'
    | '/smartops/information-management'
    | '/smartops/infrastructure'
    | '/smartops/j2-dashboard'
    | '/smartops/j3-dashboard'
    | '/smartops/j4-dashboard'
    | '/smartops/j5-dashboard'
    | '/smartops/legad-dashboard'
    | '/smartops/logistics'
    | '/smartops/mdo'
    | '/smartops/menu-builder'
    | '/smartops/ontology'
    | '/smartops/orbat'
    | '/smartops/personnel'
    | '/smartops/products'
    | '/smartops/rfis'
    | '/smartops/roe'
    | '/smartops/rxp'
    | '/smartops/scenarios'
    | '/smartops/security'
    | '/smartops/social-domain'
    | '/smartops/staff'
    | '/smartops/strategic-direction'
    | '/smartops/strike-optimizer'
    | '/smartops/supply-chain'
    | '/smartops/targeting-cell-dashboard'
    | '/smartops/tor-manager'
    | '/smartops/triage'
    | '/smartops/uncertainty'
    | '/smartops/weather'
    | '/stats/sessions'
    | '/stats/system'
    | '/stats/users'
    | '/smartops/oplan'
    | '/admin'
    | '/smartops'
    | '/admin/discovery/$serviceId'
    | '/smartops/bda/$reportId'
    | '/smartops/bda/create'
    | '/smartops/conduct/$sessionId'
    | '/smartops/proposals/$proposalId'
    | '/smartops/targeting/$targetId'
    | '/smartops/targeting/analysis'
    | '/smartops/targeting/analytics'
    | '/smartops/targeting/assets'
    | '/smartops/targeting/collaboration'
    | '/smartops/targeting/effects'
    | '/smartops/targeting/emergency'
    | '/smartops/targeting/intelligence'
    | '/smartops/targeting/jtb'
    | '/smartops/targeting/mission-command'
    | '/smartops/targeting/nominate'
    | '/smartops/targeting/risk'
    | '/smartops/targeting/targets'
    | '/admin/discovery'
    | '/smartops/proposals'
    | '/smartops/targeting'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/api-management'
    | '/debug'
    | '/login'
    | '/logs'
    | '/profile'
    | '/register'
    | '/reports'
    | '/smartops'
    | '/admin/abac'
    | '/admin/discovery'
    | '/admin/new'
    | '/admin/rate-limits'
    | '/admin/users'
    | '/smartops/a2ad'
    | '/smartops/advisory'
    | '/smartops/analyst-dashboard'
    | '/smartops/assessment'
    | '/smartops/assumptions'
    | '/smartops/battle-rhythm'
    | '/smartops/bda'
    | '/smartops/brainstorming'
    | '/smartops/briefing'
    | '/smartops/campaign'
    | '/smartops/ccir'
    | '/smartops/cde'
    | '/smartops/cnr'
    | '/smartops/coa-wargamer'
    | '/smartops/cog'
    | '/smartops/conops'
    | '/smartops/cop-summary'
    | '/smartops/decision-board'
    | '/smartops/digital-twin'
    | '/smartops/external-context'
    | '/smartops/feedback'
    | '/smartops/gap-analysis'
    | '/smartops/im-dashboard'
    | '/smartops/information-management'
    | '/smartops/infrastructure'
    | '/smartops/j2-dashboard'
    | '/smartops/j3-dashboard'
    | '/smartops/j4-dashboard'
    | '/smartops/j5-dashboard'
    | '/smartops/legad-dashboard'
    | '/smartops/logistics'
    | '/smartops/mdo'
    | '/smartops/menu-builder'
    | '/smartops/ontology'
    | '/smartops/orbat'
    | '/smartops/personnel'
    | '/smartops/products'
    | '/smartops/rfis'
    | '/smartops/roe'
    | '/smartops/rxp'
    | '/smartops/scenarios'
    | '/smartops/security'
    | '/smartops/social-domain'
    | '/smartops/staff'
    | '/smartops/strategic-direction'
    | '/smartops/strike-optimizer'
    | '/smartops/supply-chain'
    | '/smartops/targeting-cell-dashboard'
    | '/smartops/tor-manager'
    | '/smartops/triage'
    | '/smartops/uncertainty'
    | '/smartops/weather'
    | '/stats/sessions'
    | '/stats/system'
    | '/stats/users'
    | '/smartops/oplan'
    | '/admin/'
    | '/smartops/'
    | '/admin/discovery/$serviceId'
    | '/smartops/bda/$reportId'
    | '/smartops/bda/create'
    | '/smartops/conduct/$sessionId'
    | '/smartops/proposals/$proposalId'
    | '/smartops/targeting/$targetId'
    | '/smartops/targeting/analysis'
    | '/smartops/targeting/analytics'
    | '/smartops/targeting/assets'
    | '/smartops/targeting/collaboration'
    | '/smartops/targeting/effects'
    | '/smartops/targeting/emergency'
    | '/smartops/targeting/intelligence'
    | '/smartops/targeting/jtb'
    | '/smartops/targeting/mission-command'
    | '/smartops/targeting/nominate'
    | '/smartops/targeting/risk'
    | '/smartops/targeting/targets'
    | '/admin/discovery/'
    | '/smartops/proposals/'
    | '/smartops/targeting/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ApiManagementRoute: typeof ApiManagementRoute
  DebugRoute: typeof DebugRoute
  LoginRoute: typeof LoginRoute
  LogsRoute: typeof LogsRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  ReportsRoute: typeof ReportsRoute
  SmartopsRoute: typeof SmartopsRouteWithChildren
  StatsSessionsRoute: typeof StatsSessionsRoute
  StatsSystemRoute: typeof StatsSystemRoute
  StatsUsersRoute: typeof StatsUsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/smartops': {
      id: '/smartops'
      path: '/smartops'
      fullPath: '/smartops'
      preLoaderRoute: typeof SmartopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug': {
      id: '/debug'
      path: '/debug'
      fullPath: '/debug'
      preLoaderRoute: typeof DebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-management': {
      id: '/api-management'
      path: '/api-management'
      fullPath: '/api-management'
      preLoaderRoute: typeof ApiManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smartops/': {
      id: '/smartops/'
      path: '/'
      fullPath: '/smartops/'
      preLoaderRoute: typeof SmartopsIndexRouteImport
      parentRoute: typeof SmartopsRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/smartops/oplan': {
      id: '/smartops/oplan'
      path: '/oplan'
      fullPath: '/smartops/oplan'
      preLoaderRoute: typeof SmartopsOplanLazyRouteImport
      parentRoute: typeof SmartopsRoute
    }
    '/stats/users': {
      id: '/stats/users'
      path: '/stats/users'
      fullPath: '/stats/users'
      preLoaderRoute: typeof StatsUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats/system': {
      id: '/stats/system'
      path: '/stats/system'
      fullPath: '/stats/system'
      preLoaderRoute: typeof StatsSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats/sessions': {
      id: '/stats/sessions'
      path: '/stats/sessions'
      fullPath: '/stats/sessions'
      preLoaderRoute: typeof StatsSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smartops/weather': {
      id: '/smartops/weather'
      path: '/weather'
      fullPath: '/smartops/weather'
      preLoaderRoute: typeof SmartopsWeatherRouteImport
      parentRoute: typeof SmartopsRoute
    }
    '/smartops/uncertainty': {
      id: '/smartops/uncertainty'
      path: '/uncertainty'
      fullPath: '/smartops/uncertainty'
      preLoaderRoute: typeof SmartopsUncertaintyRouteImport
      parentRoute: typeof SmartopsRoute
    }
    '/smartops/triage': {
      id: '/smartops/triage'
      path: '/triage'
      fullPath: '/smartops/triage'
      preLoaderRoute: typeof SmartopsTriageRouteImport
      parentRoute: typeof SmartopsRoute
    }
    '/smartops/tor-manager': {
      id: '/smartops/tor-manager'
      path: '/tor-manager'
      fullPath: '/smartops/tor-manager'
      preLoaderRoute: typeof SmartopsTorManagerRouteImport
      parentRoute: typeof SmartopsRoute
    }
    '/smartops/targeting-cell-dashboard': {
      id: '/smartops/targeting-cell-dashboard'
      path: '/targeting-cell-dashboard'
      fullPath: '/smartops/targeting-cell-dashboard'
      preLoaderRoute: typeof SmartopsTargetingCellDashboardRouteImport
      parentRoute: typeof SmartopsRoute
    }
    '/smartops/supply-chain': {
      id: '/smartops/supply-chain'
      path: '/supply-chain'
      fullPath: '/smartops/supply-chain'
      preLoaderRoute: typeof SmartopsSupplyChainRouteImport
      parentRoute: typeof SmartopsRoute
    }
    '/smartops/strike-optimizer': {
      id: '/smartops/strike-optimizer'
      path: '/strike-optimizer'
      fullPath: '/smartops/strike-optimizer'
      preLoaderRoute: typeof SmartopsStrikeOptimizerRouteImport
      parentRoute: typeof SmartopsRoute
    }
    '/smartops/strategic-direction': {
      id: '/smartops/strategic-direction'
      path: '/strategic-direction'
      fullPath: '/smartops/strategic-direction'
      preLoaderRoute: typeof SmartopsStrategicDirectionRouteImport
      parentRoute: typeof SmartopsRoute
    }
    '/smartops/staff': {
      id: '/smartops/staff'
      path: '/staff'
      fullPath: '/smartops/staff'
      preLoaderRoute: typeof SmartopsStaffRouteImport
      parentRoute: typeof SmartopsRoute
    }
    '/smartops/social-domain': {
      id: '/smartops/social-domain'
      path: '/social-domain'
      fullPath: '/smartops/social-domain'
      preLoaderRoute: typeof SmartopsSocialDomainRouteImport
      parentRoute: typeof SmartopsRoute
    }
    '/smartops/security': {
      id: '/smartops/security'
      path: '/security'
      fullPath: '/smartops/security'
      preLoaderRoute: typeof SmartopsSecurityRouteImport
      parentRoute: typeof SmartopsRoute
    }
    '/smartops/scenarios': {
      id: '/smartops/scenarios'
      path: '/scenarios'
      fullPath: '/smartops/scenarios'
      preLoaderRoute: typeof SmartopsScenariosRouteImport
      parentRoute: typeof SmartopsRoute
    }
    '/smartops/rxp': {
      id: '/smartops/rxp'
      path: '/rxp'
      fullPath: '/smartops/rxp'
      preLoaderRoute: typeof SmartopsRxpRouteImport
      parentRoute: typeof SmartopsRoute
    }
    '/smartops/roe': {
      id: '/smartops/roe'
      path: '/roe'
      fullPath: '/smartops/roe'
      preLoaderRoute: typeof SmartopsRoeRouteImport
      parentRoute: typeof SmartopsRoute
    }
    '/smartops/rfis': {
      id: '/smartops/rfis'
      path: '/rfis'
      fullPath: '/smartops/rfis'
      preLoaderRoute: typeof SmartopsRfisRouteImport
      parentRoute: typeof SmartopsRoute
    }
    '/smartops/products': {
      id: '/smartops/products'
      path: '/products'
      fullPath: '/smartops/products'
      preLoaderRoute: typeof SmartopsProductsRouteImport
      parentRoute: typeof SmartopsRoute
    }
    '/smartops/personnel': {
      id: '/smartops/personnel'
      path: '/personnel'
      fullPath: '/smartops/personnel'
      preLoaderRoute: typeof SmartopsPersonnelRouteImport
      parentRoute: typeof SmartopsRoute
    }
    '/smartops/orbat': {
      id: '/smartops/orbat'
      path: '/orbat'
      fullPath: '/smartops/orbat'
      preLoaderRoute: typeof SmartopsOrbatRouteImport
      parentRoute: typeof SmartopsRoute
    }
    '/smartops/ontology': {
      id: '/smartops/ontology'
      path: '/ontology'
      fullPath: '/smartops/ontology'
      preLoaderRoute: typeof SmartopsOntologyRouteImport
      parentRoute: typeof SmartopsRoute
    }
    '/smartops/menu-builder': {
      id: '/smartops/menu-builder'
      path: '/menu-builder'
      fullPath: '/smartops/menu-builder'
      preLoaderRoute: typeof SmartopsMenuBuilderRouteImport
      parentRoute: typeof SmartopsRoute
    }
    '/smartops/mdo': {
      id: '/smartops/mdo'
      path: '/mdo'
      fullPath: '/smartops/mdo'
      preLoaderRoute: typeof SmartopsMdoRouteImport
      parentRoute: typeof SmartopsRoute
    }
    '/smartops/logistics': {
      id: '/smartops/logistics'
      path: '/logistics'
      fullPath: '/smartops/logistics'
      preLoaderRoute: typeof SmartopsLogisticsRouteImport
      parentRoute: typeof SmartopsRoute
    }
    '/smartops/legad-dashboard': {
      id: '/smartops/legad-dashboard'
      path: '/legad-dashboard'
      fullPath: '/smartops/legad-dashboard'
      preLoaderRoute: typeof SmartopsLegadDashboardRouteImport
      parentRoute: typeof SmartopsRoute
    }
    '/smartops/j5-dashboard': {
      id: '/smartops/j5-dashboard'
      path: '/j5-dashboard'
      fullPath: '/smartops/j5-dashboard'
      preLoaderRoute: typeof SmartopsJ5DashboardRouteImport
      parentRoute: typeof SmartopsRoute
    }
    '/smartops/j4-dashboard': {
      id: '/smartops/j4-dashboard'
      path: '/j4-dashboard'
      fullPath: '/smartops/j4-dashboard'
      preLoaderRoute: typeof SmartopsJ4DashboardRouteImport
      parentRoute: typeof SmartopsRoute
    }
    '/smartops/j3-dashboard': {
      id: '/smartops/j3-dashboard'
      path: '/j3-dashboard'
      fullPath: '/smartops/j3-dashboard'
      preLoaderRoute: typeof SmartopsJ3DashboardRouteImport
      parentRoute: typeof SmartopsRoute
    }
    '/smartops/j2-dashboard': {
      id: '/smartops/j2-dashboard'
      path: '/j2-dashboard'
      fullPath: '/smartops/j2-dashboard'
      preLoaderRoute: typeof SmartopsJ2DashboardRouteImport
      parentRoute: typeof SmartopsRoute
    }
    '/smartops/infrastructure': {
      id: '/smartops/infrastructure'
      path: '/infrastructure'
      fullPath: '/smartops/infrastructure'
      preLoaderRoute: typeof SmartopsInfrastructureRouteImport
      parentRoute: typeof SmartopsRoute
    }
    '/smartops/information-management': {
      id: '/smartops/information-management'
      path: '/information-management'
      fullPath: '/smartops/information-management'
      preLoaderRoute: typeof SmartopsInformationManagementRouteImport
      parentRoute: typeof SmartopsRoute
    }
    '/smartops/im-dashboard': {
      id: '/smartops/im-dashboard'
      path: '/im-dashboard'
      fullPath: '/smartops/im-dashboard'
      preLoaderRoute: typeof SmartopsImDashboardRouteImport
      parentRoute: typeof SmartopsRoute
    }
    '/smartops/gap-analysis': {
      id: '/smartops/gap-analysis'
      path: '/gap-analysis'
      fullPath: '/smartops/gap-analysis'
      preLoaderRoute: typeof SmartopsGapAnalysisRouteImport
      parentRoute: typeof SmartopsRoute
    }
    '/smartops/feedback': {
      id: '/smartops/feedback'
      path: '/feedback'
      fullPath: '/smartops/feedback'
      preLoaderRoute: typeof SmartopsFeedbackRouteImport
      parentRoute: typeof SmartopsRoute
    }
    '/smartops/external-context': {
      id: '/smartops/external-context'
      path: '/external-context'
      fullPath: '/smartops/external-context'
      preLoaderRoute: typeof SmartopsExternalContextRouteImport
      parentRoute: typeof SmartopsRoute
    }
    '/smartops/digital-twin': {
      id: '/smartops/digital-twin'
      path: '/digital-twin'
      fullPath: '/smartops/digital-twin'
      preLoaderRoute: typeof SmartopsDigitalTwinRouteImport
      parentRoute: typeof SmartopsRoute
    }
    '/smartops/decision-board': {
      id: '/smartops/decision-board'
      path: '/decision-board'
      fullPath: '/smartops/decision-board'
      preLoaderRoute: typeof SmartopsDecisionBoardRouteImport
      parentRoute: typeof SmartopsRoute
    }
    '/smartops/cop-summary': {
      id: '/smartops/cop-summary'
      path: '/cop-summary'
      fullPath: '/smartops/cop-summary'
      preLoaderRoute: typeof SmartopsCopSummaryRouteImport
      parentRoute: typeof SmartopsRoute
    }
    '/smartops/conops': {
      id: '/smartops/conops'
      path: '/conops'
      fullPath: '/smartops/conops'
      preLoaderRoute: typeof SmartopsConopsRouteImport
      parentRoute: typeof SmartopsRoute
    }
    '/smartops/cog': {
      id: '/smartops/cog'
      path: '/cog'
      fullPath: '/smartops/cog'
      preLoaderRoute: typeof SmartopsCogRouteImport
      parentRoute: typeof SmartopsRoute
    }
    '/smartops/coa-wargamer': {
      id: '/smartops/coa-wargamer'
      path: '/coa-wargamer'
      fullPath: '/smartops/coa-wargamer'
      preLoaderRoute: typeof SmartopsCoaWargamerRouteImport
      parentRoute: typeof SmartopsRoute
    }
    '/smartops/cnr': {
      id: '/smartops/cnr'
      path: '/cnr'
      fullPath: '/smartops/cnr'
      preLoaderRoute: typeof SmartopsCnrRouteImport
      parentRoute: typeof SmartopsRoute
    }
    '/smartops/cde': {
      id: '/smartops/cde'
      path: '/cde'
      fullPath: '/smartops/cde'
      preLoaderRoute: typeof SmartopsCdeRouteImport
      parentRoute: typeof SmartopsRoute
    }
    '/smartops/ccir': {
      id: '/smartops/ccir'
      path: '/ccir'
      fullPath: '/smartops/ccir'
      preLoaderRoute: typeof SmartopsCcirRouteImport
      parentRoute: typeof SmartopsRoute
    }
    '/smartops/campaign': {
      id: '/smartops/campaign'
      path: '/campaign'
      fullPath: '/smartops/campaign'
      preLoaderRoute: typeof SmartopsCampaignRouteImport
      parentRoute: typeof SmartopsRoute
    }
    '/smartops/briefing': {
      id: '/smartops/briefing'
      path: '/briefing'
      fullPath: '/smartops/briefing'
      preLoaderRoute: typeof SmartopsBriefingRouteImport
      parentRoute: typeof SmartopsRoute
    }
    '/smartops/brainstorming': {
      id: '/smartops/brainstorming'
      path: '/brainstorming'
      fullPath: '/smartops/brainstorming'
      preLoaderRoute: typeof SmartopsBrainstormingRouteImport
      parentRoute: typeof SmartopsRoute
    }
    '/smartops/bda': {
      id: '/smartops/bda'
      path: '/bda'
      fullPath: '/smartops/bda'
      preLoaderRoute: typeof SmartopsBdaRouteImport
      parentRoute: typeof SmartopsRoute
    }
    '/smartops/battle-rhythm': {
      id: '/smartops/battle-rhythm'
      path: '/battle-rhythm'
      fullPath: '/smartops/battle-rhythm'
      preLoaderRoute: typeof SmartopsBattleRhythmRouteImport
      parentRoute: typeof SmartopsRoute
    }
    '/smartops/assumptions': {
      id: '/smartops/assumptions'
      path: '/assumptions'
      fullPath: '/smartops/assumptions'
      preLoaderRoute: typeof SmartopsAssumptionsRouteImport
      parentRoute: typeof SmartopsRoute
    }
    '/smartops/assessment': {
      id: '/smartops/assessment'
      path: '/assessment'
      fullPath: '/smartops/assessment'
      preLoaderRoute: typeof SmartopsAssessmentRouteImport
      parentRoute: typeof SmartopsRoute
    }
    '/smartops/analyst-dashboard': {
      id: '/smartops/analyst-dashboard'
      path: '/analyst-dashboard'
      fullPath: '/smartops/analyst-dashboard'
      preLoaderRoute: typeof SmartopsAnalystDashboardRouteImport
      parentRoute: typeof SmartopsRoute
    }
    '/smartops/advisory': {
      id: '/smartops/advisory'
      path: '/advisory'
      fullPath: '/smartops/advisory'
      preLoaderRoute: typeof SmartopsAdvisoryRouteImport
      parentRoute: typeof SmartopsRoute
    }
    '/smartops/a2ad': {
      id: '/smartops/a2ad'
      path: '/a2ad'
      fullPath: '/smartops/a2ad'
      preLoaderRoute: typeof SmartopsA2adRouteImport
      parentRoute: typeof SmartopsRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rate-limits': {
      id: '/admin/rate-limits'
      path: '/rate-limits'
      fullPath: '/admin/rate-limits'
      preLoaderRoute: typeof AdminRateLimitsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/new': {
      id: '/admin/new'
      path: '/new'
      fullPath: '/admin/new'
      preLoaderRoute: typeof AdminNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/discovery': {
      id: '/admin/discovery'
      path: '/discovery'
      fullPath: '/admin/discovery'
      preLoaderRoute: typeof AdminDiscoveryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/abac': {
      id: '/admin/abac'
      path: '/abac'
      fullPath: '/admin/abac'
      preLoaderRoute: typeof AdminAbacRouteImport
      parentRoute: typeof AdminRoute
    }
    '/smartops/targeting/': {
      id: '/smartops/targeting/'
      path: '/targeting'
      fullPath: '/smartops/targeting'
      preLoaderRoute: typeof SmartopsTargetingIndexRouteImport
      parentRoute: typeof SmartopsRoute
    }
    '/smartops/proposals/': {
      id: '/smartops/proposals/'
      path: '/proposals'
      fullPath: '/smartops/proposals'
      preLoaderRoute: typeof SmartopsProposalsIndexRouteImport
      parentRoute: typeof SmartopsRoute
    }
    '/admin/discovery/': {
      id: '/admin/discovery/'
      path: '/'
      fullPath: '/admin/discovery/'
      preLoaderRoute: typeof AdminDiscoveryIndexRouteImport
      parentRoute: typeof AdminDiscoveryRoute
    }
    '/smartops/targeting/targets': {
      id: '/smartops/targeting/targets'
      path: '/targeting/targets'
      fullPath: '/smartops/targeting/targets'
      preLoaderRoute: typeof SmartopsTargetingTargetsRouteImport
      parentRoute: typeof SmartopsRoute
    }
    '/smartops/targeting/risk': {
      id: '/smartops/targeting/risk'
      path: '/targeting/risk'
      fullPath: '/smartops/targeting/risk'
      preLoaderRoute: typeof SmartopsTargetingRiskRouteImport
      parentRoute: typeof SmartopsRoute
    }
    '/smartops/targeting/nominate': {
      id: '/smartops/targeting/nominate'
      path: '/targeting/nominate'
      fullPath: '/smartops/targeting/nominate'
      preLoaderRoute: typeof SmartopsTargetingNominateRouteImport
      parentRoute: typeof SmartopsRoute
    }
    '/smartops/targeting/mission-command': {
      id: '/smartops/targeting/mission-command'
      path: '/targeting/mission-command'
      fullPath: '/smartops/targeting/mission-command'
      preLoaderRoute: typeof SmartopsTargetingMissionCommandRouteImport
      parentRoute: typeof SmartopsRoute
    }
    '/smartops/targeting/jtb': {
      id: '/smartops/targeting/jtb'
      path: '/targeting/jtb'
      fullPath: '/smartops/targeting/jtb'
      preLoaderRoute: typeof SmartopsTargetingJtbRouteImport
      parentRoute: typeof SmartopsRoute
    }
    '/smartops/targeting/intelligence': {
      id: '/smartops/targeting/intelligence'
      path: '/targeting/intelligence'
      fullPath: '/smartops/targeting/intelligence'
      preLoaderRoute: typeof SmartopsTargetingIntelligenceRouteImport
      parentRoute: typeof SmartopsRoute
    }
    '/smartops/targeting/emergency': {
      id: '/smartops/targeting/emergency'
      path: '/targeting/emergency'
      fullPath: '/smartops/targeting/emergency'
      preLoaderRoute: typeof SmartopsTargetingEmergencyRouteImport
      parentRoute: typeof SmartopsRoute
    }
    '/smartops/targeting/effects': {
      id: '/smartops/targeting/effects'
      path: '/targeting/effects'
      fullPath: '/smartops/targeting/effects'
      preLoaderRoute: typeof SmartopsTargetingEffectsRouteImport
      parentRoute: typeof SmartopsRoute
    }
    '/smartops/targeting/collaboration': {
      id: '/smartops/targeting/collaboration'
      path: '/targeting/collaboration'
      fullPath: '/smartops/targeting/collaboration'
      preLoaderRoute: typeof SmartopsTargetingCollaborationRouteImport
      parentRoute: typeof SmartopsRoute
    }
    '/smartops/targeting/assets': {
      id: '/smartops/targeting/assets'
      path: '/targeting/assets'
      fullPath: '/smartops/targeting/assets'
      preLoaderRoute: typeof SmartopsTargetingAssetsRouteImport
      parentRoute: typeof SmartopsRoute
    }
    '/smartops/targeting/analytics': {
      id: '/smartops/targeting/analytics'
      path: '/targeting/analytics'
      fullPath: '/smartops/targeting/analytics'
      preLoaderRoute: typeof SmartopsTargetingAnalyticsRouteImport
      parentRoute: typeof SmartopsRoute
    }
    '/smartops/targeting/analysis': {
      id: '/smartops/targeting/analysis'
      path: '/targeting/analysis'
      fullPath: '/smartops/targeting/analysis'
      preLoaderRoute: typeof SmartopsTargetingAnalysisRouteImport
      parentRoute: typeof SmartopsRoute
    }
    '/smartops/targeting/$targetId': {
      id: '/smartops/targeting/$targetId'
      path: '/targeting/$targetId'
      fullPath: '/smartops/targeting/$targetId'
      preLoaderRoute: typeof SmartopsTargetingTargetIdRouteImport
      parentRoute: typeof SmartopsRoute
    }
    '/smartops/proposals/$proposalId': {
      id: '/smartops/proposals/$proposalId'
      path: '/proposals/$proposalId'
      fullPath: '/smartops/proposals/$proposalId'
      preLoaderRoute: typeof SmartopsProposalsProposalIdRouteImport
      parentRoute: typeof SmartopsRoute
    }
    '/smartops/conduct/$sessionId': {
      id: '/smartops/conduct/$sessionId'
      path: '/conduct/$sessionId'
      fullPath: '/smartops/conduct/$sessionId'
      preLoaderRoute: typeof SmartopsConductSessionIdRouteImport
      parentRoute: typeof SmartopsRoute
    }
    '/smartops/bda/create': {
      id: '/smartops/bda/create'
      path: '/create'
      fullPath: '/smartops/bda/create'
      preLoaderRoute: typeof SmartopsBdaCreateRouteImport
      parentRoute: typeof SmartopsBdaRoute
    }
    '/smartops/bda/$reportId': {
      id: '/smartops/bda/$reportId'
      path: '/$reportId'
      fullPath: '/smartops/bda/$reportId'
      preLoaderRoute: typeof SmartopsBdaReportIdRouteImport
      parentRoute: typeof SmartopsBdaRoute
    }
    '/admin/discovery/$serviceId': {
      id: '/admin/discovery/$serviceId'
      path: '/$serviceId'
      fullPath: '/admin/discovery/$serviceId'
      preLoaderRoute: typeof AdminDiscoveryServiceIdRouteImport
      parentRoute: typeof AdminDiscoveryRoute
    }
  }
}

interface AdminDiscoveryRouteChildren {
  AdminDiscoveryServiceIdRoute: typeof AdminDiscoveryServiceIdRoute
  AdminDiscoveryIndexRoute: typeof AdminDiscoveryIndexRoute
}

const AdminDiscoveryRouteChildren: AdminDiscoveryRouteChildren = {
  AdminDiscoveryServiceIdRoute: AdminDiscoveryServiceIdRoute,
  AdminDiscoveryIndexRoute: AdminDiscoveryIndexRoute,
}

const AdminDiscoveryRouteWithChildren = AdminDiscoveryRoute._addFileChildren(
  AdminDiscoveryRouteChildren,
)

interface AdminRouteChildren {
  AdminAbacRoute: typeof AdminAbacRoute
  AdminDiscoveryRoute: typeof AdminDiscoveryRouteWithChildren
  AdminNewRoute: typeof AdminNewRoute
  AdminRateLimitsRoute: typeof AdminRateLimitsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAbacRoute: AdminAbacRoute,
  AdminDiscoveryRoute: AdminDiscoveryRouteWithChildren,
  AdminNewRoute: AdminNewRoute,
  AdminRateLimitsRoute: AdminRateLimitsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface SmartopsBdaRouteChildren {
  SmartopsBdaReportIdRoute: typeof SmartopsBdaReportIdRoute
  SmartopsBdaCreateRoute: typeof SmartopsBdaCreateRoute
}

const SmartopsBdaRouteChildren: SmartopsBdaRouteChildren = {
  SmartopsBdaReportIdRoute: SmartopsBdaReportIdRoute,
  SmartopsBdaCreateRoute: SmartopsBdaCreateRoute,
}

const SmartopsBdaRouteWithChildren = SmartopsBdaRoute._addFileChildren(
  SmartopsBdaRouteChildren,
)

interface SmartopsRouteChildren {
  SmartopsA2adRoute: typeof SmartopsA2adRoute
  SmartopsAdvisoryRoute: typeof SmartopsAdvisoryRoute
  SmartopsAnalystDashboardRoute: typeof SmartopsAnalystDashboardRoute
  SmartopsAssessmentRoute: typeof SmartopsAssessmentRoute
  SmartopsAssumptionsRoute: typeof SmartopsAssumptionsRoute
  SmartopsBattleRhythmRoute: typeof SmartopsBattleRhythmRoute
  SmartopsBdaRoute: typeof SmartopsBdaRouteWithChildren
  SmartopsBrainstormingRoute: typeof SmartopsBrainstormingRoute
  SmartopsBriefingRoute: typeof SmartopsBriefingRoute
  SmartopsCampaignRoute: typeof SmartopsCampaignRoute
  SmartopsCcirRoute: typeof SmartopsCcirRoute
  SmartopsCdeRoute: typeof SmartopsCdeRoute
  SmartopsCnrRoute: typeof SmartopsCnrRoute
  SmartopsCoaWargamerRoute: typeof SmartopsCoaWargamerRoute
  SmartopsCogRoute: typeof SmartopsCogRoute
  SmartopsConopsRoute: typeof SmartopsConopsRoute
  SmartopsCopSummaryRoute: typeof SmartopsCopSummaryRoute
  SmartopsDecisionBoardRoute: typeof SmartopsDecisionBoardRoute
  SmartopsDigitalTwinRoute: typeof SmartopsDigitalTwinRoute
  SmartopsExternalContextRoute: typeof SmartopsExternalContextRoute
  SmartopsFeedbackRoute: typeof SmartopsFeedbackRoute
  SmartopsGapAnalysisRoute: typeof SmartopsGapAnalysisRoute
  SmartopsImDashboardRoute: typeof SmartopsImDashboardRoute
  SmartopsInformationManagementRoute: typeof SmartopsInformationManagementRoute
  SmartopsInfrastructureRoute: typeof SmartopsInfrastructureRoute
  SmartopsJ2DashboardRoute: typeof SmartopsJ2DashboardRoute
  SmartopsJ3DashboardRoute: typeof SmartopsJ3DashboardRoute
  SmartopsJ4DashboardRoute: typeof SmartopsJ4DashboardRoute
  SmartopsJ5DashboardRoute: typeof SmartopsJ5DashboardRoute
  SmartopsLegadDashboardRoute: typeof SmartopsLegadDashboardRoute
  SmartopsLogisticsRoute: typeof SmartopsLogisticsRoute
  SmartopsMdoRoute: typeof SmartopsMdoRoute
  SmartopsMenuBuilderRoute: typeof SmartopsMenuBuilderRoute
  SmartopsOntologyRoute: typeof SmartopsOntologyRoute
  SmartopsOrbatRoute: typeof SmartopsOrbatRoute
  SmartopsPersonnelRoute: typeof SmartopsPersonnelRoute
  SmartopsProductsRoute: typeof SmartopsProductsRoute
  SmartopsRfisRoute: typeof SmartopsRfisRoute
  SmartopsRoeRoute: typeof SmartopsRoeRoute
  SmartopsRxpRoute: typeof SmartopsRxpRoute
  SmartopsScenariosRoute: typeof SmartopsScenariosRoute
  SmartopsSecurityRoute: typeof SmartopsSecurityRoute
  SmartopsSocialDomainRoute: typeof SmartopsSocialDomainRoute
  SmartopsStaffRoute: typeof SmartopsStaffRoute
  SmartopsStrategicDirectionRoute: typeof SmartopsStrategicDirectionRoute
  SmartopsStrikeOptimizerRoute: typeof SmartopsStrikeOptimizerRoute
  SmartopsSupplyChainRoute: typeof SmartopsSupplyChainRoute
  SmartopsTargetingCellDashboardRoute: typeof SmartopsTargetingCellDashboardRoute
  SmartopsTorManagerRoute: typeof SmartopsTorManagerRoute
  SmartopsTriageRoute: typeof SmartopsTriageRoute
  SmartopsUncertaintyRoute: typeof SmartopsUncertaintyRoute
  SmartopsWeatherRoute: typeof SmartopsWeatherRoute
  SmartopsOplanLazyRoute: typeof SmartopsOplanLazyRoute
  SmartopsIndexRoute: typeof SmartopsIndexRoute
  SmartopsConductSessionIdRoute: typeof SmartopsConductSessionIdRoute
  SmartopsProposalsProposalIdRoute: typeof SmartopsProposalsProposalIdRoute
  SmartopsTargetingTargetIdRoute: typeof SmartopsTargetingTargetIdRoute
  SmartopsTargetingAnalysisRoute: typeof SmartopsTargetingAnalysisRoute
  SmartopsTargetingAnalyticsRoute: typeof SmartopsTargetingAnalyticsRoute
  SmartopsTargetingAssetsRoute: typeof SmartopsTargetingAssetsRoute
  SmartopsTargetingCollaborationRoute: typeof SmartopsTargetingCollaborationRoute
  SmartopsTargetingEffectsRoute: typeof SmartopsTargetingEffectsRoute
  SmartopsTargetingEmergencyRoute: typeof SmartopsTargetingEmergencyRoute
  SmartopsTargetingIntelligenceRoute: typeof SmartopsTargetingIntelligenceRoute
  SmartopsTargetingJtbRoute: typeof SmartopsTargetingJtbRoute
  SmartopsTargetingMissionCommandRoute: typeof SmartopsTargetingMissionCommandRoute
  SmartopsTargetingNominateRoute: typeof SmartopsTargetingNominateRoute
  SmartopsTargetingRiskRoute: typeof SmartopsTargetingRiskRoute
  SmartopsTargetingTargetsRoute: typeof SmartopsTargetingTargetsRoute
  SmartopsProposalsIndexRoute: typeof SmartopsProposalsIndexRoute
  SmartopsTargetingIndexRoute: typeof SmartopsTargetingIndexRoute
}

const SmartopsRouteChildren: SmartopsRouteChildren = {
  SmartopsA2adRoute: SmartopsA2adRoute,
  SmartopsAdvisoryRoute: SmartopsAdvisoryRoute,
  SmartopsAnalystDashboardRoute: SmartopsAnalystDashboardRoute,
  SmartopsAssessmentRoute: SmartopsAssessmentRoute,
  SmartopsAssumptionsRoute: SmartopsAssumptionsRoute,
  SmartopsBattleRhythmRoute: SmartopsBattleRhythmRoute,
  SmartopsBdaRoute: SmartopsBdaRouteWithChildren,
  SmartopsBrainstormingRoute: SmartopsBrainstormingRoute,
  SmartopsBriefingRoute: SmartopsBriefingRoute,
  SmartopsCampaignRoute: SmartopsCampaignRoute,
  SmartopsCcirRoute: SmartopsCcirRoute,
  SmartopsCdeRoute: SmartopsCdeRoute,
  SmartopsCnrRoute: SmartopsCnrRoute,
  SmartopsCoaWargamerRoute: SmartopsCoaWargamerRoute,
  SmartopsCogRoute: SmartopsCogRoute,
  SmartopsConopsRoute: SmartopsConopsRoute,
  SmartopsCopSummaryRoute: SmartopsCopSummaryRoute,
  SmartopsDecisionBoardRoute: SmartopsDecisionBoardRoute,
  SmartopsDigitalTwinRoute: SmartopsDigitalTwinRoute,
  SmartopsExternalContextRoute: SmartopsExternalContextRoute,
  SmartopsFeedbackRoute: SmartopsFeedbackRoute,
  SmartopsGapAnalysisRoute: SmartopsGapAnalysisRoute,
  SmartopsImDashboardRoute: SmartopsImDashboardRoute,
  SmartopsInformationManagementRoute: SmartopsInformationManagementRoute,
  SmartopsInfrastructureRoute: SmartopsInfrastructureRoute,
  SmartopsJ2DashboardRoute: SmartopsJ2DashboardRoute,
  SmartopsJ3DashboardRoute: SmartopsJ3DashboardRoute,
  SmartopsJ4DashboardRoute: SmartopsJ4DashboardRoute,
  SmartopsJ5DashboardRoute: SmartopsJ5DashboardRoute,
  SmartopsLegadDashboardRoute: SmartopsLegadDashboardRoute,
  SmartopsLogisticsRoute: SmartopsLogisticsRoute,
  SmartopsMdoRoute: SmartopsMdoRoute,
  SmartopsMenuBuilderRoute: SmartopsMenuBuilderRoute,
  SmartopsOntologyRoute: SmartopsOntologyRoute,
  SmartopsOrbatRoute: SmartopsOrbatRoute,
  SmartopsPersonnelRoute: SmartopsPersonnelRoute,
  SmartopsProductsRoute: SmartopsProductsRoute,
  SmartopsRfisRoute: SmartopsRfisRoute,
  SmartopsRoeRoute: SmartopsRoeRoute,
  SmartopsRxpRoute: SmartopsRxpRoute,
  SmartopsScenariosRoute: SmartopsScenariosRoute,
  SmartopsSecurityRoute: SmartopsSecurityRoute,
  SmartopsSocialDomainRoute: SmartopsSocialDomainRoute,
  SmartopsStaffRoute: SmartopsStaffRoute,
  SmartopsStrategicDirectionRoute: SmartopsStrategicDirectionRoute,
  SmartopsStrikeOptimizerRoute: SmartopsStrikeOptimizerRoute,
  SmartopsSupplyChainRoute: SmartopsSupplyChainRoute,
  SmartopsTargetingCellDashboardRoute: SmartopsTargetingCellDashboardRoute,
  SmartopsTorManagerRoute: SmartopsTorManagerRoute,
  SmartopsTriageRoute: SmartopsTriageRoute,
  SmartopsUncertaintyRoute: SmartopsUncertaintyRoute,
  SmartopsWeatherRoute: SmartopsWeatherRoute,
  SmartopsOplanLazyRoute: SmartopsOplanLazyRoute,
  SmartopsIndexRoute: SmartopsIndexRoute,
  SmartopsConductSessionIdRoute: SmartopsConductSessionIdRoute,
  SmartopsProposalsProposalIdRoute: SmartopsProposalsProposalIdRoute,
  SmartopsTargetingTargetIdRoute: SmartopsTargetingTargetIdRoute,
  SmartopsTargetingAnalysisRoute: SmartopsTargetingAnalysisRoute,
  SmartopsTargetingAnalyticsRoute: SmartopsTargetingAnalyticsRoute,
  SmartopsTargetingAssetsRoute: SmartopsTargetingAssetsRoute,
  SmartopsTargetingCollaborationRoute: SmartopsTargetingCollaborationRoute,
  SmartopsTargetingEffectsRoute: SmartopsTargetingEffectsRoute,
  SmartopsTargetingEmergencyRoute: SmartopsTargetingEmergencyRoute,
  SmartopsTargetingIntelligenceRoute: SmartopsTargetingIntelligenceRoute,
  SmartopsTargetingJtbRoute: SmartopsTargetingJtbRoute,
  SmartopsTargetingMissionCommandRoute: SmartopsTargetingMissionCommandRoute,
  SmartopsTargetingNominateRoute: SmartopsTargetingNominateRoute,
  SmartopsTargetingRiskRoute: SmartopsTargetingRiskRoute,
  SmartopsTargetingTargetsRoute: SmartopsTargetingTargetsRoute,
  SmartopsProposalsIndexRoute: SmartopsProposalsIndexRoute,
  SmartopsTargetingIndexRoute: SmartopsTargetingIndexRoute,
}

const SmartopsRouteWithChildren = SmartopsRoute._addFileChildren(
  SmartopsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ApiManagementRoute: ApiManagementRoute,
  DebugRoute: DebugRoute,
  LoginRoute: LoginRoute,
  LogsRoute: LogsRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  ReportsRoute: ReportsRoute,
  SmartopsRoute: SmartopsRouteWithChildren,
  StatsSessionsRoute: StatsSessionsRoute,
  StatsSystemRoute: StatsSystemRoute,
  StatsUsersRoute: StatsUsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
